from decimal import Decimal
from sqlalchemy import Date,ForeignKey,Index,Numeric,SmallInteger,String,Text,text
from sqlalchemy.orm import Mapped,mapped_column,relationship
from app.db.base import Base,TimestampMixin
class BOLStatus: DRAFT=0;GENERATED=1;PRINTED=2;COMPLETED=3;CANCELED=4
class BOL(TimestampMixin,Base):
 __tablename__='bols';__table_args__=(Index('uq_bols_active_outbound','outbound_order_id',unique=True,postgresql_where=text('status <> 4'),sqlite_where=text('status <> 4')),);id:Mapped[int]=mapped_column(primary_key=True);bol_no:Mapped[str]=mapped_column(String(24),unique=True,index=True);outbound_order_id:Mapped[int]=mapped_column(ForeignKey('outbound_orders.id',ondelete='RESTRICT'),index=True);fba_shipment_id:Mapped[int|None]=mapped_column(ForeignKey('fba_shipments.id',ondelete='SET NULL'),index=True);customer_id:Mapped[int|None]=mapped_column(ForeignKey('customers.id',ondelete='RESTRICT'));warehouse_id:Mapped[int]=mapped_column(ForeignKey('warehouses.id',ondelete='RESTRICT'));carrier_id:Mapped[int|None]=mapped_column(ForeignKey('carriers.id',ondelete='RESTRICT'));ship_from_name:Mapped[str]=mapped_column(String(200));ship_from_address:Mapped[str]=mapped_column(Text);ship_to_name:Mapped[str|None]=mapped_column(String(200));ship_to_address:Mapped[str|None]=mapped_column(Text);amazon_fc_code:Mapped[str|None]=mapped_column(String(20));pickup_date:Mapped[str|None]=mapped_column(Date);appointment_time:Mapped[str|None]=mapped_column(String(40));status:Mapped[int]=mapped_column(SmallInteger,default=0,index=True);special_instructions:Mapped[str|None]=mapped_column(Text);created_by:Mapped[int]=mapped_column(ForeignKey('users.id',ondelete='RESTRICT'));outbound=relationship('OutboundOrder');fba_shipment=relationship('FBAShipment');warehouse=relationship('Warehouse');carrier=relationship('Carrier');customer=relationship('Customer');creator=relationship('User');items=relationship('BOLItem',back_populates='bol',cascade='all, delete-orphan')
class BOLItem(Base):
 __tablename__='bol_items';id:Mapped[int]=mapped_column(primary_key=True);bol_id:Mapped[int]=mapped_column(ForeignKey('bols.id',ondelete='CASCADE'),index=True);outbound_allocation_id:Mapped[int]=mapped_column(ForeignKey('outbound_inventory_allocations.id',ondelete='RESTRICT'),index=True);inventory_lot_id:Mapped[int]=mapped_column(ForeignKey('inventory_lots.id',ondelete='RESTRICT'),index=True);container_number:Mapped[str|None]=mapped_column(String(50));fc_code:Mapped[str|None]=mapped_column(String(20));marking:Mapped[str|None]=mapped_column(String(100));pallet_qty:Mapped[Decimal]=mapped_column(Numeric(12,2),default=0);carton_qty:Mapped[Decimal]=mapped_column(Numeric(12,2),default=0);weight_lbs:Mapped[Decimal]=mapped_column(Numeric(14,2),default=0);cbm:Mapped[Decimal]=mapped_column(Numeric(14,4),default=0);description:Mapped[str|None]=mapped_column(Text);bol=relationship('BOL',back_populates='items');outbound_allocation=relationship('OutboundInventoryAllocation');inventory_lot=relationship('InventoryLot')
