import enum
from datetime import datetime,time
from decimal import Decimal
from sqlalchemy import CheckConstraint,DateTime,ForeignKey,Numeric,SmallInteger,String,Text,Time,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column,relationship
from app.db.base import Base,TimestampMixin

class FBAStatus(enum.IntEnum):DRAFT=0;PLANNING=1;ALLOCATED=2;READY=3;SCHEDULED=4;IN_TRANSIT=5;DELIVERED=6;COMPLETED=7;HOLD=8;CANCELED=9
class FBAShipment(TimestampMixin,Base):
    __tablename__="fba_shipments";__table_args__=(CheckConstraint("status BETWEEN 0 AND 9",name="status_range"),)
    id:Mapped[int]=mapped_column(primary_key=True);fba_no:Mapped[str]=mapped_column(String(24),unique=True,index=True);customer_id:Mapped[int|None]=mapped_column(ForeignKey("customers.id",ondelete="RESTRICT"),index=True);warehouse_id:Mapped[int]=mapped_column(ForeignKey("warehouses.id",ondelete="RESTRICT"),index=True);amazon_fc_code:Mapped[str]=mapped_column(String(20),index=True);amazon_fc_address_id:Mapped[int|None]=mapped_column(ForeignKey("amazon_fc_addresses.id",ondelete="SET NULL"),index=True);status:Mapped[int]=mapped_column(SmallInteger,default=0,index=True);scheduled_pickup_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));appointment_time:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),index=True);carrier_id:Mapped[int|None]=mapped_column(ForeignKey("carriers.id",ondelete="RESTRICT"),index=True);reference_no:Mapped[str|None]=mapped_column(String(100),index=True);shipment_id:Mapped[str|None]=mapped_column(String(100),index=True);st_number:Mapped[str|None]=mapped_column(String(100),index=True);po_number:Mapped[str|None]=mapped_column(String(200),index=True);source_reference:Mapped[str|None]=mapped_column(String(200),index=True);import_job_id:Mapped[int|None]=mapped_column(ForeignKey("import_jobs.id",ondelete="SET NULL"),index=True);remark:Mapped[str|None]=mapped_column(Text);created_by:Mapped[int]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));customer=relationship("Customer");warehouse=relationship("Warehouse");amazon_fc_address=relationship("AmazonFCAddress");carrier=relationship("Carrier");creator=relationship("User");allocations=relationship("FBAInventoryAllocation",back_populates="shipment",cascade="all, delete-orphan")
class FBAInventoryAllocation(TimestampMixin,Base):
    __tablename__="fba_inventory_allocations";__table_args__=(UniqueConstraint("fba_shipment_id","inventory_lot_id",name="uq_fba_lot_allocation"),CheckConstraint("allocated_pallet_qty >= 0 AND allocated_carton_qty >= 0 AND allocated_weight_lbs >= 0 AND allocated_cbm >= 0",name="quantities_non_negative"))
    id:Mapped[int]=mapped_column(primary_key=True);fba_shipment_id:Mapped[int]=mapped_column(ForeignKey("fba_shipments.id",ondelete="CASCADE"),index=True);inventory_lot_id:Mapped[int]=mapped_column(ForeignKey("inventory_lots.id",ondelete="RESTRICT"),index=True);import_row_id:Mapped[int|None]=mapped_column(ForeignKey("import_rows.id",ondelete="SET NULL"),index=True);allocated_pallet_qty:Mapped[Decimal]=mapped_column(Numeric(12,2),default=0);allocated_carton_qty:Mapped[Decimal]=mapped_column(Numeric(12,2),default=0);allocated_weight_lbs:Mapped[Decimal]=mapped_column(Numeric(14,2),default=0);allocated_cbm:Mapped[Decimal]=mapped_column(Numeric(14,4),default=0);created_by:Mapped[int]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));shipment=relationship("FBAShipment",back_populates="allocations");inventory_lot=relationship("InventoryLot");creator=relationship("User")
