import enum
from datetime import date,datetime
from decimal import Decimal
from typing import Any
from sqlalchemy import Boolean,CheckConstraint,Date,DateTime,Enum,ForeignKey,Integer,JSON,Numeric,SmallInteger,String,Text,UniqueConstraint,func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped,mapped_column,relationship
from app.db.base import Base,TimestampMixin

JsonType=JSON().with_variant(JSONB(),"postgresql")
class InventoryStatus(enum.IntEnum):AVAILABLE=0;PARTIALLY_ALLOCATED=1;FULLY_ALLOCATED=2;HOLD=3;DEPLETED=4;CLOSED=5
class TransactionType(str,enum.Enum):INBOUND="INBOUND";MOVE="MOVE";ADJUSTMENT="ADJUSTMENT";HOLD="HOLD";RELEASE="RELEASE";FBA_ALLOCATE="FBA_ALLOCATE";FBA_RELEASE="FBA_RELEASE";OUTBOUND_ALLOCATE="OUTBOUND_ALLOCATE";OUTBOUND_RELEASE="OUTBOUND_RELEASE";OUTBOUND_COMPLETE="OUTBOUND_COMPLETE"

class InventoryLot(TimestampMixin,Base):
    __tablename__="inventory_lots";__table_args__=(
        CheckConstraint("original_pallet_qty >= 0 AND available_pallet_qty >= 0 AND allocated_pallet_qty >= 0 AND hold_pallet_qty >= 0",name="pallet_non_negative"),CheckConstraint("available_pallet_qty + allocated_pallet_qty + hold_pallet_qty <= original_pallet_qty",name="pallet_balance"),
        CheckConstraint("original_carton_qty >= 0 AND available_carton_qty >= 0 AND allocated_carton_qty >= 0 AND hold_carton_qty >= 0",name="carton_non_negative"),CheckConstraint("available_carton_qty + allocated_carton_qty + hold_carton_qty <= original_carton_qty",name="carton_balance"),
        CheckConstraint("original_weight_lbs >= 0 AND available_weight_lbs >= 0 AND allocated_weight_lbs >= 0",name="weight_non_negative"),CheckConstraint("available_weight_lbs + allocated_weight_lbs <= original_weight_lbs",name="weight_balance"),
        CheckConstraint("original_cbm >= 0 AND available_cbm >= 0 AND allocated_cbm >= 0",name="cbm_non_negative"),CheckConstraint("available_cbm + allocated_cbm <= original_cbm",name="cbm_balance"),CheckConstraint("status BETWEEN 0 AND 5",name="status_range"),)
    id:Mapped[int]=mapped_column(primary_key=True);lot_no:Mapped[str]=mapped_column(String(24),unique=True,index=True);customer_id:Mapped[int|None]=mapped_column(ForeignKey("customers.id",ondelete="RESTRICT"),index=True);warehouse_id:Mapped[int]=mapped_column(ForeignKey("warehouses.id",ondelete="RESTRICT"),index=True);source_inbound_id:Mapped[int]=mapped_column(ForeignKey("inbound_records.id",ondelete="RESTRICT"),index=True);inbound_line_id:Mapped[int|None]=mapped_column(ForeignKey("inbound_lines.id",ondelete="RESTRICT"),unique=True,index=True);container_number:Mapped[str]=mapped_column(String(50),index=True);fc_code:Mapped[str|None]=mapped_column(String(20),index=True);marking:Mapped[str|None]=mapped_column(String(100));location_id:Mapped[int|None]=mapped_column(ForeignKey("warehouse_locations.id",ondelete="RESTRICT"),index=True);raw_location_text:Mapped[str|None]=mapped_column(Text);import_row_id:Mapped[int|None]=mapped_column(ForeignKey("import_rows.id",ondelete="SET NULL"),index=True)
    original_pallet_qty:Mapped[Decimal]=mapped_column(Numeric(12,2));original_carton_qty:Mapped[Decimal]=mapped_column(Numeric(12,2));original_weight_lbs:Mapped[Decimal]=mapped_column(Numeric(14,2));original_cbm:Mapped[Decimal]=mapped_column(Numeric(14,4));available_pallet_qty:Mapped[Decimal]=mapped_column(Numeric(12,2));available_carton_qty:Mapped[Decimal]=mapped_column(Numeric(12,2));available_weight_lbs:Mapped[Decimal]=mapped_column(Numeric(14,2));available_cbm:Mapped[Decimal]=mapped_column(Numeric(14,4));allocated_pallet_qty:Mapped[Decimal]=mapped_column(Numeric(12,2),default=0);allocated_carton_qty:Mapped[Decimal]=mapped_column(Numeric(12,2),default=0);allocated_weight_lbs:Mapped[Decimal]=mapped_column(Numeric(14,2),default=0);allocated_cbm:Mapped[Decimal]=mapped_column(Numeric(14,4),default=0);hold_pallet_qty:Mapped[Decimal]=mapped_column(Numeric(12,2),default=0);hold_carton_qty:Mapped[Decimal]=mapped_column(Numeric(12,2),default=0)
    inbound_date:Mapped[date|None]=mapped_column(Date,index=True);status:Mapped[int]=mapped_column(SmallInteger,default=0,index=True);remark:Mapped[str|None]=mapped_column(Text);created_by:Mapped[int]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"),index=True)
    customer=relationship("Customer");warehouse=relationship("Warehouse");location=relationship("WarehouseLocation");source_inbound=relationship("InboundRecord",back_populates="inventory_lots");inbound_line=relationship("InboundLine",back_populates="inventory_lot");creator=relationship("User");transactions=relationship("InventoryTransaction",back_populates="lot",cascade="all, delete-orphan");lot_locations=relationship("InventoryLotLocation",back_populates="inventory_lot",cascade="all, delete-orphan")

class InventoryLotLocation(TimestampMixin,Base):
    __tablename__="inventory_lot_locations";__table_args__=(UniqueConstraint("inventory_lot_id","location_id",name="uq_inventory_lot_location"),)
    id:Mapped[int]=mapped_column(primary_key=True);inventory_lot_id:Mapped[int]=mapped_column(ForeignKey("inventory_lots.id",ondelete="CASCADE"),index=True);location_id:Mapped[int]=mapped_column(ForeignKey("warehouse_locations.id",ondelete="RESTRICT"),index=True);pallet_qty:Mapped[Decimal|None]=mapped_column(Numeric(12,2));carton_qty:Mapped[Decimal|None]=mapped_column(Numeric(12,2));inventory_lot=relationship("InventoryLot",back_populates="lot_locations");location=relationship("WarehouseLocation")

class InventoryTransaction(Base):
    __tablename__="inventory_transactions"
    id:Mapped[int]=mapped_column(primary_key=True);inventory_lot_id:Mapped[int]=mapped_column(ForeignKey("inventory_lots.id",ondelete="RESTRICT"),index=True);transaction_type:Mapped[TransactionType]=mapped_column(Enum(TransactionType,name="inventory_transaction_type"),index=True);pallet_delta:Mapped[Decimal]=mapped_column(Numeric(12,2),default=0);carton_delta:Mapped[Decimal]=mapped_column(Numeric(12,2),default=0);weight_delta:Mapped[Decimal]=mapped_column(Numeric(14,2),default=0);cbm_delta:Mapped[Decimal]=mapped_column(Numeric(14,4),default=0);from_location_id:Mapped[int|None]=mapped_column(ForeignKey("warehouse_locations.id",ondelete="RESTRICT"));to_location_id:Mapped[int|None]=mapped_column(ForeignKey("warehouse_locations.id",ondelete="RESTRICT"));reference_type:Mapped[str|None]=mapped_column(String(50));reference_id:Mapped[int|None]=mapped_column(Integer);before_snapshot:Mapped[dict[str,Any]|None]=mapped_column(JsonType);after_snapshot:Mapped[dict[str,Any]|None]=mapped_column(JsonType);remark:Mapped[str|None]=mapped_column(Text);created_by:Mapped[int]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),index=True)
    lot=relationship("InventoryLot",back_populates="transactions");from_location=relationship("WarehouseLocation",foreign_keys=[from_location_id]);to_location=relationship("WarehouseLocation",foreign_keys=[to_location_id]);creator=relationship("User")

class InventoryPriorityRule(TimestampMixin,Base):
    __tablename__="inventory_priority_rules";__table_args__=(UniqueConstraint("priority_level",name="uq_inventory_priority_level"),CheckConstraint("min_days >= 0",name="min_days_non_negative"),CheckConstraint("max_days IS NULL OR max_days >= min_days",name="day_range"))
    id:Mapped[int]=mapped_column(primary_key=True);min_days:Mapped[int]=mapped_column(Integer);max_days:Mapped[int|None]=mapped_column(Integer);priority_level:Mapped[str]=mapped_column(String(20));priority_label:Mapped[str]=mapped_column(String(50));sort_order:Mapped[int]=mapped_column(Integer);is_active:Mapped[bool]=mapped_column(Boolean,default=True,server_default="true")
