from datetime import datetime
from decimal import Decimal
from sqlalchemy import CheckConstraint,DateTime,ForeignKey,Numeric,SmallInteger,String,Text
from sqlalchemy.orm import Mapped,mapped_column,relationship
from app.db.base import Base,TimestampMixin
class PickingStatus: NEW=0;PRINTED=1;IN_PROGRESS=2;COMPLETED=3;CANCELED=4;EXCEPTION=5
class PickingList(TimestampMixin,Base):
 __tablename__='picking_lists';id:Mapped[int]=mapped_column(primary_key=True);picking_no:Mapped[str]=mapped_column(String(24),unique=True,index=True);outbound_order_id:Mapped[int]=mapped_column(ForeignKey('outbound_orders.id',ondelete='RESTRICT'),index=True);status:Mapped[int]=mapped_column(SmallInteger,default=0,index=True);assigned_team:Mapped[str|None]=mapped_column(String(100));assigned_to:Mapped[int|None]=mapped_column(ForeignKey('users.id',ondelete='SET NULL'));printed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));printed_by:Mapped[int|None]=mapped_column(ForeignKey('users.id',ondelete='SET NULL'));started_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));started_by:Mapped[int|None]=mapped_column(ForeignKey('users.id',ondelete='SET NULL'));completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));completed_by:Mapped[int|None]=mapped_column(ForeignKey('users.id',ondelete='SET NULL'));canceled_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));canceled_by:Mapped[int|None]=mapped_column(ForeignKey('users.id',ondelete='SET NULL'));remark:Mapped[str|None]=mapped_column(Text);created_by:Mapped[int]=mapped_column(ForeignKey('users.id',ondelete='RESTRICT'));outbound=relationship('OutboundOrder');creator=relationship('User',foreign_keys=[created_by]);items=relationship('PickingListItem',back_populates='picking',cascade='all, delete-orphan')
class PickingListItem(TimestampMixin,Base):
 cargo_bol_no:Mapped[str|None]=mapped_column(String(24))
 po_number:Mapped[str|None]=mapped_column(Text)
 __tablename__='picking_list_items';id:Mapped[int]=mapped_column(primary_key=True);picking_list_id:Mapped[int]=mapped_column(ForeignKey('picking_lists.id',ondelete='CASCADE'),index=True);outbound_allocation_id:Mapped[int]=mapped_column(ForeignKey('outbound_inventory_allocations.id',ondelete='RESTRICT'),index=True);inventory_lot_id:Mapped[int]=mapped_column(ForeignKey('inventory_lots.id',ondelete='RESTRICT'),index=True);location_id:Mapped[int|None]=mapped_column(ForeignKey('warehouse_locations.id',ondelete='RESTRICT'),index=True);lot_no:Mapped[str]=mapped_column(String(24));container_number:Mapped[str]=mapped_column(String(50));fc_code:Mapped[str|None]=mapped_column(String(20));marking:Mapped[str|None]=mapped_column(String(100));planned_pallet_qty:Mapped[Decimal]=mapped_column(Numeric(12,2),default=0);planned_carton_qty:Mapped[Decimal]=mapped_column(Numeric(12,2),default=0);planned_weight_lbs:Mapped[Decimal]=mapped_column(Numeric(14,2),default=0);planned_cbm:Mapped[Decimal]=mapped_column(Numeric(14,4),default=0);picked_pallet_qty:Mapped[Decimal]=mapped_column(Numeric(12,2),default=0);picked_carton_qty:Mapped[Decimal]=mapped_column(Numeric(12,2),default=0);picked_weight_lbs:Mapped[Decimal]=mapped_column(Numeric(14,2),default=0);picked_cbm:Mapped[Decimal]=mapped_column(Numeric(14,4),default=0);sequence_no:Mapped[int]=mapped_column(SmallInteger,default=1);remark:Mapped[str|None]=mapped_column(Text);picking=relationship('PickingList',back_populates='items');outbound_allocation=relationship('OutboundInventoryAllocation');inventory_lot=relationship('InventoryLot');location=relationship('WarehouseLocation')
