import{InboxOutlined}from'@ant-design/icons';
import{Alert,Button,Checkbox,Descriptions,Modal,Progress,Radio,Select,Space,Statistic,Steps,Table,Tag,Upload,message}from'antd';
import{useEffect,useMemo,useState}from'react';import{useLocation}from'react-router-dom';
import{confirmImport,downloadImportErrors,getImportProfiles,getImportProgress,getValidationResult,inspectWorkbook,previewImport,previewProfile,validateImport,validateImportAsync,type ImportModule}from'../api/imports';
import{getWarehouses}from'../api/masterData';
import type{ColumnMapping,ImportPreview,ImportProfile,ImportProgress as ProgressState,ImportSummary,ImportValidationResult,WorkbookInspection}from'../types/imports';
import type{Warehouse}from'../types/masterData';

const commonFields=[['','Do not import'],['container_number','Container Number'],['customer','Customer'],['warehouse','Warehouse'],['fc_code','FC Code'],['location','Location'],['pallet_qty','Pallet Qty'],['carton_qty','Carton Qty'],['weight_lbs','Weight LBS'],['cbm','CBM'],['remark','Remark']];
const inboundFields=[...commonFields,['unload_date','Unload Date'],['received_date','Received Date'],['weight_kg','Weight KG'],['fba_reference','FBA Reference'],['po_number','PO Number']];
const fbaFields=[...commonFields,['fba_no','FBA No'],['shipment_id','Shipment ID'],['amazon_fc_code','Amazon FC'],['st_number','ST Number'],['po_number','PO Number'],['source_reference','Source OL Reference'],['weight_unknown_unit','Weight (Unknown Unit)']];
const outboundFields=[...commonFields,['ob_no','Outbound No'],['appointment_reference','Appointment Reference'],['delivery_appointment_time','Delivery Appointment'],['actual_outbound_time','Actual Outbound Time'],['picking_reference','External Picking'],['bol_reference','External BOL'],['planned_pallet_qty','Planned Pallets'],['planned_carton_qty','Planned Cartons'],['planned_weight_lbs','Planned Weight'],['planned_cbm','Planned CBM'],['completed_pallet_qty','Completed Pallets'],['completed_carton_qty','Completed Cartons'],['completed_weight_lbs','Completed Weight'],['completed_cbm','Completed CBM'],['redirect_code','Redirect Code'],['pod_reference','POD'],['po_number','PO'],['fba_no','FBA'],['source_reference','Inventory References']];
const moduleName={inbound:'Inbound',fba:'FBA',outbound:'Outbound'};
const moduleEnum={inbound:'INBOUND',fba:'FBA',outbound:'OUTBOUND'};

export function ImportWizard({open,onClose,onComplete,module:requestedModule='inbound'}:{open:boolean;onClose:()=>void;onComplete:()=>void;module?:ImportModule}){
 const module=useLocation().pathname.startsWith('/outbound')?'outbound':requestedModule;const fields=module==='fba'?fbaFields:module==='outbound'?outboundFields:inboundFields;
 const[step,setStep]=useState(0);const[loading,setLoading]=useState(false);const[file,setFile]=useState<File|null>(null);const[inspection,setInspection]=useState<WorkbookInspection|null>(null);const[profiles,setProfiles]=useState<ImportProfile[]>([]);const[warehouses,setWarehouses]=useState<Warehouse[]>([]);const[sheet,setSheet]=useState('');const[profile,setProfile]=useState('GENERIC');const[warehouseId,setWarehouseId]=useState<number>();const[preview,setPreview]=useState<ImportPreview|null>(null);const[mapping,setMapping]=useState<ColumnMapping>({});const[validation,setValidation]=useState<ImportValidationResult|null>(null);const[progress,setProgress]=useState<ProgressState|null>(null);const[result,setResult]=useState<ImportSummary|null>(null);const[strategy,setStrategy]=useState<'SKIP'|'UPDATE'>('SKIP');const[autoLocation,setAutoLocation]=useState(false);const[autoReceive,setAutoReceive]=useState(false);const[includeWarnings,setIncludeWarnings]=useState(true);
 const relevantProfiles=useMemo(()=>profiles.filter(p=>p.module===moduleEnum[module]),[profiles,module]);
 useEffect(()=>{if(open)Promise.all([getImportProfiles(),getWarehouses()]).then(([p,w])=>{setProfiles(p);setWarehouses(w);setWarehouseId(x=>x??w[0]?.id)}).catch(()=>message.error('Master data could not be loaded'))},[open]);
 const reset=()=>{setStep(0);setFile(null);setInspection(null);setSheet('');setProfile('GENERIC');setPreview(null);setMapping({});setValidation(null);setProgress(null);setResult(null);setStrategy('SKIP');setAutoLocation(false);setAutoReceive(false)};
 async function upload(selected:File){setLoading(true);setFile(selected);try{const info=await inspectWorkbook(selected);setInspection(info);const preferred=Object.entries(info.suggested_profiles).find(([,code])=>relevantProfiles.some(p=>p.code===code));if(preferred){setSheet(preferred[0]);setProfile(preferred[1])}else{setSheet(info.sheet_names[0]??'');setProfile('GENERIC')}setStep(1)}catch{message.error('Workbook inspection failed')}finally{setLoading(false)}return false}
 function selectSheet(value:string){setSheet(value);const suggested=inspection?.suggested_profiles[value];setProfile(suggested&&relevantProfiles.some(p=>p.code===suggested)?suggested:'GENERIC')}
 async function prepare(){if(!file||!inspection||!sheet||!warehouseId)return message.warning('Select Sheet, Profile, and Warehouse');setLoading(true);try{const p=profile==='GENERIC'?await previewImport(module,file):await previewProfile(inspection.upload_token,sheet,profile,warehouseId);setPreview(p);setMapping(p.suggested_mapping);setStep(2)}catch{message.error('Selected sheet preview failed')}finally{setLoading(false)}}
 async function validate(){if(!preview)return;const targets=Object.values(mapping).filter(Boolean);if(new Set(targets).size!==targets.length)return message.error('A system field cannot be mapped twice');setLoading(true);try{if(profile==='GENERIC'){setValidation(await validateImport(module,preview.job_id,mapping))}else{await validateImportAsync(preview.job_id);for(let attempt=0;attempt<2400;attempt++){const current=await getImportProgress(preview.job_id);setProgress(current);if(current.status==='READY'){setValidation(await getValidationResult(preview.job_id));break}if(current.status==='FAILED')throw new Error('Validation failed');await new Promise(resolve=>setTimeout(resolve,500))}if(!validation&&progress?.status==='VALIDATING')throw new Error('Validation timed out')}setStep(3)}catch{message.error('Mapping or validation failed')}finally{setLoading(false)}}
 async function confirm(){if(!preview)return;setLoading(true);try{const r=await confirmImport(module,preview.job_id,mapping,strategy,{include_warning_rows:includeWarnings,auto_create_location:autoLocation,auto_receive_to_inventory:autoReceive});setResult(r);setStep(5);onComplete()}catch{message.error('Import failed or duplicate file requires an explicit strategy')}finally{setLoading(false)}}
 return<Modal title={`${moduleName[module]} Excel Import`}width="min(1240px,96vw)"open={open}onCancel={()=>{onClose();reset()}}footer={null}destroyOnHidden><Steps size="small"current={step}items={['Upload','Select Sheet / Profile','Mapping','Validation','Confirm','Result'].map(title=>({title}))}/><div className="wizard-body">
 {step===0&&<Upload.Dragger accept=".xlsx,.csv"showUploadList={false}beforeUpload={upload}disabled={loading}><p className="ant-upload-drag-icon"><InboxOutlined/></p><p>Upload WPS/Excel .xlsx or UTF-8 CSV</p><small>Large workbooks are streamed to the server; the browser never parses the workbook.</small></Upload.Dragger>}
 {step===1&&inspection&&<><Alert type={inspection.west_coast_4_0_detected?'success':'info'}showIcon message={inspection.west_coast_4_0_detected?'West Coast 4.0 workbook detected':'Workbook inspected'}description={`${(inspection.file_size/1024/1024).toFixed(1)} MiB · Select exactly one Sheet to import.`}/><Space wrap style={{margin:'20px 0'}}><Select style={{width:220}}value={sheet}onChange={selectSheet}options={inspection.sheet_names.map(name=>({value:name,label:`${name} (${inspection.sheet_row_estimates[name]??'?'} rows)`}))}/><Select style={{width:260}}value={profile}onChange={setProfile}options={[{value:'GENERIC',label:`Generic ${moduleName[module]}`},...relevantProfiles.map(p=>({value:p.code,label:p.name,disabled:p.sheet_name!==sheet}))]}/><Select style={{width:260}}value={warehouseId}onChange={setWarehouseId}options={warehouses.map(w=>({value:w.id,label:`${w.warehouse_code} — ${w.warehouse_name}`}))}/></Space><Alert type="warning"showIcon message="Recommended import order: 1. OL  2. Verify Inventory  3. DS  4. Verify FBA  5. 出库"/><div className="wizard-actions"><Button onClick={()=>setStep(0)}>Back</Button><Button type="primary"loading={loading}onClick={prepare}>Read Selected Sheet</Button></div></>}
 {step===2&&preview&&<><Alert type="info"showIcon message={`${preview.total_rows} rows staged. Only the first ${preview.preview_rows.length} rows are returned to the browser.`}/><Table size="small"pagination={false}dataSource={preview.detected_columns.map((column,i)=>({key:i,column}))}columns={[{title:'Excel Column',dataIndex:'column'},{title:'System Field',render:(_,r)=><Select value={mapping[r.column]}style={{width:250}}options={fields.map(([value,label])=>({value,label,disabled:!!value&&Object.entries(mapping).some(([source,target])=>source!==r.column&&target===value)}))}onChange={value=>setMapping(current=>({...current,[r.column]:value}))}/>}]}scroll={{y:390}}/><div className="wizard-actions"><Button onClick={()=>setStep(1)}>Back</Button><Button type="primary"loading={loading}onClick={validate}>Validate</Button></div></>}
 {step===3&&validation&&<><div className="summary-row"><Statistic title="Total"value={validation.total_rows}/><Statistic title="Valid"value={validation.valid_rows}/><Statistic title="Warnings"value={validation.warning_rows}valueStyle={{color:'#d48806'}}/><Statistic title="Errors"value={validation.error_rows}valueStyle={{color:'#cf1322'}}/></div>{progress&&<><Progress percent={Math.round(progress.progress_percent*10)/10}/><p>{progress.current_stage} rows {progress.processed_rows.toLocaleString()} / {progress.total_rows.toLocaleString()}</p></>} {validation.rows_per_second&&<Alert type="info"message={`${validation.duration_seconds}s · ${validation.rows_per_second.toLocaleString()} rows/sec`}/>}<Table rowClassName={r=>r.status==='ERROR'?'row-error':r.status==='WARNING'?'row-warning':''}size="small"pagination={false}dataSource={validation.rows}rowKey="row_number"columns={[{title:'Row',dataIndex:'row_number',width:65},{title:'Reference',render:(_,r)=>String(r.data.container_number??r.data.ob_no??'')},{title:'FC',render:(_,r)=>String(r.data.amazon_fc_code??r.data.fc_code??'')},{title:'Status',render:(_,r)=><Space direction="vertical"size={0}><Tag color={r.status==='ERROR'?'red':r.status==='WARNING'?'gold':'green'}>{r.status}</Tag>{r.issues.map(x=><small key={x.code+x.column}>{x.code}: {x.message}</small>)}</Space>}]}scroll={{x:900,y:350}}/><Space><Button disabled={!validation.error_rows}onClick={()=>preview&&downloadImportErrors(preview.job_id)}>Download Errors.xlsx</Button></Space><div className="wizard-actions"><Button onClick={()=>setStep(2)}>Back</Button><Button type="primary"disabled={validation.valid_rows===0}onClick={()=>setStep(4)}>Continue</Button></div></>}
 {step===4&&validation&&<div className="confirm-step"><Alert type={validation.error_rows?'warning':'success'}showIcon message={`${validation.valid_rows} valid/warning rows available; error rows cannot import.`}/><h3>Duplicate Strategy</h3><Radio.Group value={strategy}onChange={event=>setStrategy(event.target.value)}><Radio value="SKIP">Cancel/skip previously imported data (recommended)</Radio><Radio value="UPDATE">Explicit re-run/update</Radio></Radio.Group><div style={{marginTop:18}}><Space direction="vertical"><Checkbox checked={includeWarnings}onChange={e=>setIncludeWarnings(e.target.checked)}>Import valid + warning rows</Checkbox>{module==='inbound'&&<Checkbox checked={autoLocation}onChange={e=>setAutoLocation(e.target.checked)}>AUTO_CREATE_LOCATION (confirmed warehouse only)</Checkbox>}{module==='inbound'&&<Checkbox checked={autoReceive}onChange={e=>setAutoReceive(e.target.checked)}>AUTO_RECEIVE_TO_INVENTORY (dated, valid rows only)</Checkbox>}</Space></div><div className="wizard-actions"><Button onClick={()=>setStep(3)}>Back</Button><Button type="primary"loading={loading}onClick={confirm}>Confirm Import</Button></div></div>}
 {step===5&&result&&<div className="result-step"><Alert type="success"showIcon message="Import completed"/><div className="summary-row"><Statistic title="Total"value={result.total_rows}/><Statistic title="Imported"value={result.imported_rows}/><Statistic title="Skipped"value={result.skipped_rows}/><Statistic title="Warnings"value={result.warning_rows}/><Statistic title="Errors"value={result.error_rows}/></div>{result.reconciliation&&<Descriptions bordered size="small"column={1}items={Object.entries(result.reconciliation).map(([key,value])=>({key,label:key,children:<pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(value,null,2)}</pre>}))}/>}<Button type="primary"onClick={()=>{onClose();reset()}}>Done</Button></div>}
 </div></Modal>
}
