import { ArrowLeftOutlined, ArrowRightOutlined, CloseOutlined, DownloadOutlined } from '@ant-design/icons'
import { Alert, Button, Descriptions, Empty, Form, Input, InputNumber, Modal, Skeleton, Space, Table, Tabs, Tag, Typography, message } from 'antd'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { getFBAWorkbenchDetail } from '../../api/fbaWorkbench'
import { createOutbound, updateOutbound } from '../../api/outbound'
import { downloadFile, generateBol, generatePicking } from '../../api/pickingBol'
import type { FBAWorkbenchRow } from '../../types/fbaWorkbench'
import { FBAWorkflow } from './FBAWorkflow'

const value = (x: unknown) => x === null || x === undefined || x === '' ? '-' : String(x)
const dateTime = (x: unknown) => x ? new Date(String(x)).toLocaleString('en-US') : '-'
export function FBADetailPanel({ row, onClose, onPrev, onNext, onAllocate }: { row: FBAWorkbenchRow | null; onClose: () => void; onPrev: () => void; onNext: () => void; onAllocate?: () => void }) {
  const qc = useQueryClient(); const [scheduleOpen, setScheduleOpen] = useState(false); const [form] = Form.useForm(); const detail = useQuery({ queryKey: ['fba-workbench-detail', row?.id], queryFn: () => getFBAWorkbenchDetail(row!.id), enabled: !!row })
  const refresh = () => { qc.invalidateQueries({ queryKey: ['fba-workbench'] }); qc.invalidateQueries({ queryKey: ['fba-workbench-detail', row?.id] }) }
  const picking = useMutation({ mutationFn: () => generatePicking(row!.outbound_id!), onSuccess: () => { message.success('Picking created'); refresh() }, onError: () => message.error('Picking requires outbound allocations') })
  const bol = useMutation({ mutationFn: () => generateBol(row!.outbound_id!), onSuccess: () => { message.success('BOL created'); refresh() }, onError: () => message.error('Unable to create BOL') })
  const outbound = useMutation({ mutationFn: () => createOutbound({ warehouse_id: row!.warehouse_id, fba_shipment_id: row!.id, customer_id: detail.data?.basic.customer_id || null, ob_type: 'FBA', fc_code: row!.amazon_fc_code, reference_no: row!.fba_no }), onSuccess: () => { message.success('Outbound created'); refresh() }, onError: () => message.error('Unable to create Outbound') })
  const schedule = useMutation({ mutationFn: (data: Record<string, unknown>) => updateOutbound(row!.outbound_id!, { warehouse_id: row!.warehouse_id, customer_id: null, fba_shipment_id: row!.id, ob_type: 'FBA', ...data }), onSuccess: () => { message.success('Schedule saved'); setScheduleOpen(false); refresh() }, onError: () => message.error('Unable to save schedule') })
  if (!row) return <div className="detail-empty"><Empty description="Select an FBA task" /></div>
  if (detail.isLoading) return <div className="detail-loading"><Skeleton active /></div>
  if (detail.isError || !detail.data) return <Alert type="error" message="Failed to load detail" action={<Button onClick={() => detail.refetch()}>Retry</Button>} />
  const d = detail.data; const b = d.basic
  const inventory = <Table size="small" rowKey="id" pagination={false} scroll={{ x: 1100 }} dataSource={d.inventory_sources} columns={['lot_no','container_number','fc_code','location','inbound_date','aging_days','allocated_pallet_qty','allocated_carton_qty','allocated_weight_lbs','allocated_cbm'].map(k => ({ title: k.replaceAll('_', ' '), dataIndex: k, render: (v: unknown) => typeof v === 'object' && v ? (v as { code?: string }).code || '-' : value(v) }))} />
  const basic = <><Descriptions size="small" column={2} items={Object.entries({ Customer: b.customer, Warehouse: b.warehouse, 'Amazon FC': b.amazon_fc_code, 'ST Number': b.st_number, 'Shipment ID': b.shipment_id, PO: b.po_number, Carrier: b.carrier, Appointment: dateTime(b.appointment_time), 'Scheduled Pickup': dateTime(b.scheduled_pickup_at), Created: dateTime(b.created_at), Remark: b.remark }).map(([label, v]) => ({ label, children: value(v) }))} />{b.fc_address_missing && <Alert type="warning" showIcon message="Amazon FC address missing" />}<Typography.Title level={5}>Workflow</Typography.Title><FBAWorkflow steps={d.workflow} /></>
  const pick = d.picking.length ? d.picking.map((x: any) => <div className="detail-card" key={x.id}><b>{x.picking_no}</b><Tag>{x.status_name}</Tag><span>{x.planned_pallet_qty} PLT</span><Button icon={<DownloadOutlined />} onClick={() => downloadFile(`/picking-lists/${x.id}/xlsx`, `${x.picking_no}.xlsx`)}>XLSX</Button></div>) : <Empty description="No picking list" />
  const amazon = <Descriptions column={1} items={Object.entries({ FC: b.amazon_fc_code, Name: b.amazon_fc_name, Address: b.amazon_fc_address, ST: b.st_number, Shipment: b.shipment_id, PO: b.po_number, Appointment: dateTime(b.appointment_time) }).map(([label, v]) => ({ label, children: value(v) }))} />
  const bolTab = d.bol ? <div className="detail-card"><b>{value(d.bol.bol_no)}</b><Tag>{value(d.bol.status_name)}</Tag><Button onClick={() => downloadFile(`/bols/${d.bol!.id}/pdf`, `${d.bol!.bol_no}.pdf`)}>PDF</Button><Button onClick={() => downloadFile(`/bols/${d.bol!.id}/xlsx`, `${d.bol!.bol_no}.xlsx`)}>XLSX</Button></div> : <Empty description="No BOL" />
  const audit = <Table size="small" pagination={false} rowKey={(_, i) => String(i)} dataSource={d.audit} columns={[{ title: 'Time', dataIndex: 'time', render: dateTime }, { title: 'User', dataIndex: 'user' }, { title: 'Action', dataIndex: 'action' }, { title: 'Entity', dataIndex: 'entity' }]} />
  const outboundData = d.outbound as Record<string, unknown> | null
  const openSchedule = () => { if (outboundData) { form.setFieldsValue({ carrier_id: outboundData.carrier_id, schedule_pickup_at: outboundData.schedule_pickup_at?.toString().slice(0, 16), delivery_appointment_time: outboundData.delivery_appointment_time?.toString().slice(0, 16), driver_name: outboundData.driver_name, truck_number: outboundData.truck_number, trailer_number: outboundData.trailer_number, remark: outboundData.remark }); setScheduleOpen(true) } }
  return <div className="fba-detail"><div className="detail-head"><div><Typography.Title level={5}>{row.fba_no}</Typography.Title><Tag color="orange">{row.workbench_stage_name}</Tag></div><Space><Button icon={<ArrowLeftOutlined />} onClick={onPrev} /><Button icon={<ArrowRightOutlined />} onClick={onNext} /><Button icon={<CloseOutlined />} onClick={onClose} /></Space></div><Tabs items={[{ key: 'basic', label: 'Basic', children: basic }, { key: 'inventory', label: 'Inventory Sources', children: inventory }, { key: 'picking', label: 'Picking', children: pick }, { key: 'amazon', label: 'Amazon Info', children: amazon }, { key: 'bol', label: 'BOL', children: bolTab }, { key: 'audit', label: 'Audit', children: audit }]} /><div className="quick-actions"><Button onClick={onAllocate}>Allocate Inventory</Button><Button disabled={!d.permissions.can_operate || !!row.picking_id || !row.outbound_id} loading={picking.isPending} onClick={() => picking.mutate()}>{row.picking_id ? 'View Picking' : 'Generate Picking'}</Button><Button disabled={!d.permissions.can_operate || !!row.bol_id || !row.outbound_id} loading={bol.isPending} onClick={() => bol.mutate()}>{row.bol_id ? 'View BOL' : 'Generate BOL'}</Button><Button type="primary" disabled={!d.permissions.can_operate || !!row.outbound_id} loading={outbound.isPending} onClick={() => outbound.mutate()}>{row.outbound_id ? 'View Outbound' : 'Create Outbound'}</Button><Button disabled={!row.outbound_id || !d.permissions.can_operate} onClick={openSchedule}>Schedule / APT</Button></div><Modal title="Schedule / Appointment" open={scheduleOpen} onCancel={() => setScheduleOpen(false)} onOk={() => form.submit()} confirmLoading={schedule.isPending}><Form form={form} layout="vertical" onFinish={values => schedule.mutate({ ...values, schedule_pickup_at: values.schedule_pickup_at || null, delivery_appointment_time: values.delivery_appointment_time || null })}><Form.Item name="carrier_id" label="Carrier"><InputNumber min={1} /></Form.Item><Form.Item name="schedule_pickup_at" label="Scheduled Pickup"><Input type="datetime-local" /></Form.Item><Form.Item name="delivery_appointment_time" label="Appointment Time"><Input type="datetime-local" /></Form.Item><Form.Item name="driver_name" label="Driver"><Input /></Form.Item><Form.Item name="truck_number" label="Truck Number"><Input /></Form.Item><Form.Item name="trailer_number" label="Trailer Number"><Input /></Form.Item><Form.Item name="remark" label="Remark"><Input.TextArea /></Form.Item></Form></Modal></div>
}
