from datetime import date,timedelta
from fastapi.testclient import TestClient
from sqlalchemy import select
from sqlalchemy.orm import Session
from app.models import FBAInventoryAllocation,InventoryLot,InventoryTransaction,Warehouse,WarehouseArea,WarehouseLocation

def make_lot(client,seed,container="FBA-CNTR",fc="ONT8",pallet=5,days=22):
    data={"container_number":container,"customer_id":seed["customer"].id,"warehouse_id":seed["warehouse"].id,"received_date":str(date.today()-timedelta(days=days)),"fc_code":fc,"pallet_qty":pallet,"carton_qty":50,"weight_lbs":5000,"cbm":20,"location_id":seed["location"].id,"status":3};ib=client.post("/api/v1/inbound",json=data).json();return client.post(f"/api/v1/inbound/{ib['id']}/receive-to-inventory").json()
def fba_payload(seed,fc="ONT8"):return{"customer_id":seed["customer"].id,"warehouse_id":seed["warehouse"].id,"amazon_fc_code":fc,"carrier_id":seed["carrier"].id,"reference_no":"REF-FBA","shipment_id":"SHIP-1","st_number":"ST-1"}
def test_create_number_fc_link_and_list(client:TestClient,seed):
    first=client.post("/api/v1/fba",json=fba_payload(seed));assert first.status_code==201,first.text;body=first.json();assert body["fba_no"].startswith(f"FBA{date.today():%y%m%d}");assert body["amazon_fc_name"]=="Amazon ONT8";assert body["fc_address_missing"]is False
    second=client.post("/api/v1/fba",json=fba_payload(seed,"GYR2")).json();assert int(second["fba_no"][-4:])==int(body["fba_no"][-4:])+1;assert second["fc_address_missing"]is True;listed=client.get("/api/v1/fba",params={"q":"REF-FBA","amazon_fc_code":"ONT8","warehouse_id":seed["warehouse"].id}).json();assert listed["meta"]["total"]==1
def test_allocate_partial_overallocation_totals_aging_priority(client:TestClient,db:Session,seed):
    lot=make_lot(client,seed);fba=client.post("/api/v1/fba",json=fba_payload(seed)).json();url=f"/api/v1/fba/{fba['id']}/allocate";first=client.post(url,json={"inventory_lot_id":lot["id"],"pallet_qty":3,"carton_qty":20,"weight_lbs":2000,"cbm":8});assert first.status_code==200,first.text
    assert client.post(url,json={"inventory_lot_id":lot["id"],"pallet_qty":3,"carton_qty":0,"weight_lbs":0,"cbm":0}).status_code==409;db.expire_all();stored=db.get(InventoryLot,lot["id"]);assert stored.available_pallet_qty==2;assert stored.allocated_pallet_qty==3
    detail=client.get(f"/api/v1/fba/{fba['id']}").json();assert detail["total_pallet_qty"]=="3.00";assert detail["inventory_lot_count"]==1;assert detail["max_aging_days"]>=22;assert detail["priority_level"]=="RED";tx=db.scalars(select(InventoryTransaction).where(InventoryTransaction.transaction_type=="FBA_ALLOCATE")).first();assert tx.reference_type=="FBA";assert tx.reference_id==fba["id"]
def test_fc_mismatch_requires_confirmation(client:TestClient,seed):
    lot=make_lot(client,seed,fc="LAX9");fba=client.post("/api/v1/fba",json=fba_payload(seed)).json();url=f"/api/v1/fba/{fba['id']}/allocate";assert client.post(url,json={"inventory_lot_id":lot["id"],"pallet_qty":1}).status_code==409;r=client.post(url,json={"inventory_lot_id":lot["id"],"pallet_qty":1,"confirm_fc_mismatch":True});assert r.status_code==200;assert r.json()["fc_mismatch"]is True
def test_cross_warehouse_rejected(client:TestClient,db:Session,seed):
    lot=make_lot(client,seed);other=Warehouse(warehouse_code="OTHER-FBA",warehouse_name="Other",address="x",city="x",state="CA",zip_code="1");db.add(other);db.commit();fba=client.post("/api/v1/fba",json={**fba_payload(seed),"warehouse_id":other.id}).json();assert client.post(f"/api/v1/fba/{fba['id']}/allocate",json={"inventory_lot_id":lot["id"],"pallet_qty":1}).status_code==409
def test_partial_release_and_over_release(client:TestClient,db:Session,seed):
    lot=make_lot(client,seed);fba=client.post("/api/v1/fba",json=fba_payload(seed)).json();allocation=client.post(f"/api/v1/fba/{fba['id']}/allocate",json={"inventory_lot_id":lot["id"],"pallet_qty":5,"carton_qty":10}).json();url=f"/api/v1/fba/{fba['id']}/allocations/{allocation['id']}/release";released=client.post(url,json={"pallet_qty":2,"carton_qty":4,"weight_lbs":0,"cbm":0});assert released.status_code==200;assert released.json()["allocated_pallet_qty"]=="3.00";assert client.post(url,json={"pallet_qty":4}).status_code==409;db.expire_all();stored=db.get(InventoryLot,lot["id"]);assert stored.available_pallet_qty==2;assert stored.allocated_pallet_qty==3
def test_cancel_releases_all_and_status_transitions(client:TestClient,db:Session,seed):
    lot=make_lot(client,seed,pallet=10);fba=client.post("/api/v1/fba",json=fba_payload(seed)).json();client.post(f"/api/v1/fba/{fba['id']}/allocate",json={"inventory_lot_id":lot["id"],"pallet_qty":10});canceled=client.post(f"/api/v1/fba/{fba['id']}/status",json={"status":9});assert canceled.status_code==200,canceled.text;assert canceled.json()["status_name"]=="Canceled";db.expire_all();stored=db.get(InventoryLot,lot["id"]);assert stored.available_pallet_qty==10;assert stored.allocated_pallet_qty==0;allocation=db.scalar(select(FBAInventoryAllocation));assert allocation.allocated_pallet_qty==0;assert client.post(f"/api/v1/fba/{fba['id']}/status",json={"status":1}).status_code==409
