from datetime import date
from fastapi.testclient import TestClient
from sqlalchemy import select
from sqlalchemy.orm import Session
from app.models import InventoryLot,OutboundInventoryAllocation,OutboundOrder,FBAInventoryAllocation
def inventory(client,seed,container='OB-CNTR',pallet=10):
 p={'container_number':container,'customer_id':seed['customer'].id,'warehouse_id':seed['warehouse'].id,'received_date':str(date.today()),'fc_code':'ONT8','pallet_qty':pallet,'carton_qty':20,'weight_lbs':1000,'cbm':5,'location_id':seed['location'].id,'status':3};i=client.post('/api/v1/inbound',json=p).json();return client.post(f"/api/v1/inbound/{i['id']}/receive-to-inventory").json()
def ob(seed):return {'customer_id':seed['customer'].id,'warehouse_id':seed['warehouse'].id,'carrier_id':seed['carrier'].id,'ob_type':'STANDARD','delivery_type':'FTL'}
def test_normal_outbound_lifecycle(client:TestClient,db:Session,seed):
 lot=inventory(client,seed);o=client.post('/api/v1/outbounds',json=ob(seed)).json();a=client.post(f"/api/v1/outbounds/{o['id']}/allocate",json={'inventory_lot_id':lot['id'],'pallet_qty':6});assert a.status_code==200,a.text;assert client.post(f"/api/v1/outbounds/{o['id']}/confirm").status_code==200;assert client.post(f"/api/v1/outbounds/{o['id']}/dispatch").status_code==200;done=client.post(f"/api/v1/outbounds/{o['id']}/complete");assert done.status_code==200,done.text;db.expire_all();x=db.get(InventoryLot,lot['id']);assert x.available_pallet_qty==4 and x.allocated_pallet_qty==0;assert client.post(f"/api/v1/outbounds/{o['id']}/allocate",json={'inventory_lot_id':lot['id'],'pallet_qty':1}).status_code==409
def test_overallocation_and_cancel_release(client:TestClient,db:Session,seed):
 lot=inventory(client,seed,pallet=5);o=client.post('/api/v1/outbounds',json=ob(seed)).json();u=f"/api/v1/outbounds/{o['id']}/allocate";assert client.post(u,json={'inventory_lot_id':lot['id'],'pallet_qty':4}).status_code==200;assert client.post(u,json={'inventory_lot_id':lot['id'],'pallet_qty':3}).status_code==409;assert client.post(f"/api/v1/outbounds/{o['id']}/cancel").status_code==200;db.expire_all();assert db.get(InventoryLot,lot['id']).available_pallet_qty==5
def test_exception_and_fba_outbound_balance(client:TestClient,db:Session,seed):
 lot=inventory(client,seed,pallet=10);f=client.post('/api/v1/fba',json={'warehouse_id':seed['warehouse'].id,'customer_id':seed['customer'].id,'amazon_fc_code':'ONT8'}).json();fa=client.post(f"/api/v1/fba/{f['id']}/allocate",json={'inventory_lot_id':lot['id'],'pallet_qty':10}).json();o=client.post('/api/v1/outbounds',json={**ob(seed),'ob_type':'FBA','fba_shipment_id':f['id'],'fc_code':'ONT8'}).json();a=client.post(f"/api/v1/outbounds/{o['id']}/allocate",json={'inventory_lot_id':lot['id'],'fba_allocation_id':fa['id'],'pallet_qty':6});assert a.status_code==200,a.text;db.expire_all();assert db.get(InventoryLot,lot['id']).allocated_pallet_qty==10;assert client.post(f"/api/v1/outbounds/{o['id']}/cancel").status_code==200;db.expire_all();assert db.get(InventoryLot,lot['id']).allocated_pallet_qty==10;assert db.get(FBAInventoryAllocation,fa['id']).allocated_pallet_qty==10
