from tests.dispatch_history import mark_historical_dispatched
from datetime import date
from fastapi.testclient import TestClient
from sqlalchemy import select
from sqlalchemy.orm import Session
from app.models import AuditLog,BOL,FBAInventoryAllocation,InventoryLot,OutboundInventoryAllocation,OutboundOrder,PickingList,PickingStatus
def inventory(client,seed,container='OB-CNTR',pallet=10):
 p={'container_number':container,'customer_id':seed['customer'].id,'warehouse_id':seed['warehouse'].id,'received_date':str(date.today()),'fc_code':'ONT8','pallet_qty':pallet,'carton_qty':20,'weight_lbs':1000,'cbm':5,'location_id':seed['location'].id,'status':3};i=client.post('/api/v1/inbound',json=p).json();return client.post(f"/api/v1/inbound/{i['id']}/receive-to-inventory").json()
def ob(seed):return {'customer_id':seed['customer'].id,'warehouse_id':seed['warehouse'].id,'carrier_id':seed['carrier'].id,'ob_type':'STANDARD','delivery_type':'FTL'}

def test_create_booking_preserves_sources_and_inventory(client,db,seed):
 lot=inventory(client,seed,container='BOOKING-SOURCE');source=client.post('/api/v1/outbounds',json=ob(seed)).json()
 db.get(OutboundOrder,source['id']).bol_reference='BOL-BOOKING';db.commit()
 response=client.post('/api/v1/outbounds',json={**ob(seed),'ob_type':'Consol','delivery_type':'FBA','truck_type':"53' FTL",'booked_pallet_qty':12.5,'appointment_reference':'APT-123','related_outbound_ids':[source['id'],source['id']]})
 assert response.status_code==201,response.text
 created=response.json();assert float(created['booked_pallet_qty'])==12.5;assert created['appointment_reference']=='APT-123';assert len(created['related_bols'])==1;assert created['related_bols'][0]['outbound_id']==source['id']
 detail=client.get(f"/api/v1/outbounds/{created['id']}/workbench-detail").json()['basic'];assert detail['warehouse_id']==seed['warehouse'].id;assert float(detail['booked_pallet_qty'])==12.5
 db.expire_all();assert db.get(InventoryLot,lot['id']).available_pallet_qty==10;assert db.get(OutboundOrder,source['id']).bol_reference=='BOL-BOOKING';assert db.scalar(select(OutboundInventoryAllocation).where(OutboundInventoryAllocation.outbound_order_id==created['id'])) is None
 assert client.post('/api/v1/outbounds',json={**ob(seed),'booked_pallet_qty':-1}).status_code==422
 assert client.post('/api/v1/outbounds',json={**ob(seed),'related_outbound_ids':[999999]}).status_code==404

def test_normal_outbound_lifecycle(client:TestClient,db:Session,seed):
 lot=inventory(client,seed);o=client.post('/api/v1/outbounds',json=ob(seed)).json();a=client.post(f"/api/v1/outbounds/{o['id']}/allocate",json={'inventory_lot_id':lot['id'],'pallet_qty':6});assert a.status_code==200,a.text;assert client.post(f"/api/v1/outbounds/{o['id']}/confirm").status_code==200
 picking=db.scalar(select(PickingList).where(PickingList.outbound_order_id==o['id']));assert picking is not None;[setattr(item,'picked_pallet_qty',item.planned_pallet_qty) for item in picking.items];picking.status=PickingStatus.COMPLETED;assert db.scalar(select(BOL).where(BOL.outbound_order_id==o['id'])) is not None;db.commit()
 assert client.post(f"/api/v1/outbounds/{o['id']}/dispatch").status_code==409;mark_historical_dispatched(db,o['id']);done=client.post(f"/api/v1/outbounds/{o['id']}/complete");assert done.status_code==200,done.text;db.expire_all();x=db.get(InventoryLot,lot['id']);assert x.available_pallet_qty==4 and x.allocated_pallet_qty==0;assert client.post(f"/api/v1/outbounds/{o['id']}/allocate",json={'inventory_lot_id':lot['id'],'pallet_qty':1}).status_code==409
def test_overallocation_and_cancel_release(client:TestClient,db:Session,seed):
 lot=inventory(client,seed,pallet=5);o=client.post('/api/v1/outbounds',json=ob(seed)).json();u=f"/api/v1/outbounds/{o['id']}/allocate";assert client.post(u,json={'inventory_lot_id':lot['id'],'pallet_qty':4}).status_code==200;assert client.post(u,json={'inventory_lot_id':lot['id'],'pallet_qty':3}).status_code==409;assert client.post(f"/api/v1/outbounds/{o['id']}/cancel").status_code==200;db.expire_all();assert db.get(InventoryLot,lot['id']).available_pallet_qty==5
def test_exception_and_fba_outbound_balance(client:TestClient,db:Session,seed):
 lot=inventory(client,seed,pallet=10);f=client.post('/api/v1/fba',json={'warehouse_id':seed['warehouse'].id,'customer_id':seed['customer'].id,'amazon_fc_code':'ONT8'}).json();fa=client.post(f"/api/v1/fba/{f['id']}/allocate",json={'inventory_lot_id':lot['id'],'pallet_qty':10}).json();o=client.post('/api/v1/outbounds',json={**ob(seed),'ob_type':'FBA','fba_shipment_id':f['id'],'fc_code':'ONT8'}).json();a=client.post(f"/api/v1/outbounds/{o['id']}/allocate",json={'inventory_lot_id':lot['id'],'fba_allocation_id':fa['id'],'pallet_qty':6});assert a.status_code==200,a.text;db.expire_all();assert db.get(InventoryLot,lot['id']).allocated_pallet_qty==10;assert client.post(f"/api/v1/outbounds/{o['id']}/cancel").status_code==200;db.expire_all();assert db.get(InventoryLot,lot['id']).allocated_pallet_qty==10;assert db.get(FBAInventoryAllocation,fa['id']).allocated_pallet_qty==10
def test_workbench_sources_expose_current_quantities_for_batch_move(client:TestClient,db:Session,seed):
 lot=inventory(client,seed,container='BATCH-MOVE',pallet=10);standard=client.post('/api/v1/outbounds',json=ob(seed)).json();standard_source=client.get(f"/api/v1/outbounds/{standard['id']}/workbench-detail").json()['remaining_sources'][0];assert standard_source['available_pallet_qty']=='10.00';assert standard_source['available_weight_lbs']=='1000.00';assert standard_source['available_cbm']=='5.0000'
 f=client.post('/api/v1/fba',json={'warehouse_id':seed['warehouse'].id,'customer_id':seed['customer'].id,'amazon_fc_code':'ONT8'}).json();fa=client.post(f"/api/v1/fba/{f['id']}/allocate",json={'inventory_lot_id':lot['id'],'pallet_qty':10,'carton_qty':20,'weight_lbs':1000,'cbm':5}).json();outbound=client.post('/api/v1/outbounds',json={**ob(seed),'ob_type':'FBA','fba_shipment_id':f['id'],'fc_code':'ONT8'}).json();allocated=client.post(f"/api/v1/outbounds/{outbound['id']}/allocate",json={'inventory_lot_id':lot['id'],'fba_allocation_id':fa['id'],'pallet_qty':6,'carton_qty':12,'weight_lbs':600,'cbm':3});assert allocated.status_code==200,allocated.text
 sources=client.get(f"/api/v1/outbounds/{outbound['id']}/workbench-detail").json()['remaining_sources'];assert len(sources)==1;source=sources[0];assert source['inventory_lot_id']==lot['id'];assert source['remaining_pallet_qty']=='4.00';assert source['remaining_carton_qty']=='8.00';assert source['remaining_weight_lbs']=='400.00';assert source['remaining_cbm']=='2.0000'
def test_batch_delete_only_removes_pristine_new_drafts(client:TestClient,db:Session,seed):
 clean=client.post('/api/v1/outbounds',json={**ob(seed),'reference_no':'DELETE-ME'}).json();blocked=client.post('/api/v1/outbounds',json={**ob(seed),'reference_no':'KEEP-ME'}).json();lot=inventory(client,seed,container='DELETE-BLOCKER');assert client.post(f"/api/v1/outbounds/{blocked['id']}/allocate",json={'inventory_lot_id':lot['id'],'pallet_qty':1}).status_code==200
 rows=client.get('/api/v1/outbounds/workbench',params={'per_page':100}).json()['data'];by_id={row['id']:row for row in rows};assert by_id[clean['id']]['allowed_actions']['delete'] is True;assert by_id[blocked['id']]['allowed_actions']['delete'] is False
 response=client.post('/api/v1/outbounds/workbench/batch',json={'action':'delete','ids':[clean['id'],blocked['id']]});assert response.status_code==200,response.text;result=response.json();assert result['successful']==1 and result['failed']==1;assert 'inventory allocation' in result['results'][1]['reason']
 db.expire_all();assert db.get(OutboundOrder,clean['id']) is None;assert db.get(OutboundOrder,blocked['id']) is not None;audit=db.scalar(select(AuditLog).where(AuditLog.action=='DELETE_OUTBOUND',AuditLog.entity_id==clean['id']));assert audit is not None;assert audit.before_data['ob_no']==clean['ob_no'] and audit.before_data['reference_no']=='DELETE-ME'
def test_inventory_batch_move_preserves_successes_and_reports_blocked_rows(client:TestClient,db:Session,seed):
 lot=inventory(client,seed,container='BATCH-ENDPOINT',pallet=5);outbound=client.post('/api/v1/outbounds',json=ob(seed)).json();url=f"/api/v1/outbounds/{outbound['id']}/inventory/batch"
 response=client.post(url,json={'action':'allocate','items':[{'id':101,'data':{'inventory_lot_id':lot['id'],'pallet_qty':3}},{'id':102,'data':{'inventory_lot_id':lot['id'],'pallet_qty':9}}]});assert response.status_code==200,response.text;result=response.json();assert result['successful']==1 and result['failed']==1;assert result['results'][0]=={'id':101,'status':'success'};assert 'exceeds available inventory' in result['results'][1]['reason']
 db.expire_all();stored_lot=db.get(InventoryLot,lot['id']);assert stored_lot.available_pallet_qty==2;allocation=db.scalar(select(OutboundInventoryAllocation).where(OutboundInventoryAllocation.outbound_order_id==outbound['id']));assert allocation.allocated_pallet_qty==3
 response=client.post(url,json={'action':'release','items':[{'id':allocation.id,'data':{'allocation_id':allocation.id}},{'id':999999,'data':{'allocation_id':999999}}]});assert response.status_code==200,response.text;result=response.json();assert result['successful']==1 and result['failed']==1;assert result['results'][0]=={'id':allocation.id,'status':'success'};assert 'not found' in result['results'][1]['reason']
 db.expire_all();assert db.get(InventoryLot,lot['id']).available_pallet_qty==5
