from app.services.outbound_bol_metadata import bol_metadata
from app.services.history_policy import history_job_ids, HISTORY_LABEL
from datetime import date
from decimal import Decimal
from math import ceil
from sqlalchemy import func,or_,select
from sqlalchemy.orm import Session,joinedload,selectinload
from app.models import AuditLog,BOL,FBAInventoryAllocation,FBAShipment,InventoryLot,OutboundInventoryAllocation,OutboundOrder,PickingList,PickingListItem,User,Warehouse
from app.models.outbound import OBStatus
from app.models.picking import PickingStatus
from app.models.user import UserRole
from app.services.outbound import STATUS,allocations,read_ob,get_ob,outbound_ids_with_delete_links
from app.services.picking_bol import BOL_NAMES,PICK_NAMES,bol_read,picking_read
from app.services.dispatch_priority import container_dispatch_aggregate,dispatch_fields
from app.services.access_policy import customer_clause, warehouse_clause
from app.services.dispatch_readiness import get_dispatch_readiness
ZERO=Decimal(0)
def can_write(u):return u.role in {UserRole.ADMIN,UserRole.MANAGER,UserRole.OUTBOUND,UserRole.WAREHOUSE}
def _numbers(o):
    allocated={x:sum((getattr(a,f'allocated_{x}') for a in o.allocations),ZERO) for x in ('pallet_qty','carton_qty','weight_lbs','cbm')};completed={x:sum((getattr(a,f'completed_{x}') for a in o.allocations),ZERO) for x in allocated};picked={x:sum((i.picked_pallet_qty if x=='pallet_qty' else i.picked_carton_qty if x=='carton_qty' else i.picked_weight_lbs if x=='weight_lbs' else i.picked_cbm for p in o.pickings for i in p.items),ZERO) if hasattr(o,'pickings') else ZERO for x in allocated};return allocated,completed,picked
def list_workbench(db:Session,user:User,**p):
    q=select(OutboundOrder).options(joinedload(OutboundOrder.customer),joinedload(OutboundOrder.warehouse),joinedload(OutboundOrder.carrier),joinedload(OutboundOrder.fba_shipment),selectinload(OutboundOrder.allocations).joinedload(OutboundInventoryAllocation.inventory_lot),selectinload(OutboundOrder.allocations).joinedload(OutboundInventoryAllocation.fba_allocation)).outerjoin(FBAShipment,FBAShipment.id==OutboundOrder.fba_shipment_id);f=[]
    for scope in (warehouse_clause(user,OutboundOrder.warehouse_id),customer_clause(user,OutboundOrder.customer_id)):
        if scope is not None:f.append(scope)
    if p.get('warehouse_id'):f.append(OutboundOrder.warehouse_id==p['warehouse_id'])
    if p.get('status') is not None:f.append(OutboundOrder.status==p['status'])
    if p.get('ob_type'):f.append(OutboundOrder.ob_type==p['ob_type'])
    if p.get('carrier_id'):f.append(OutboundOrder.carrier_id==p['carrier_id'])
    if p.get('order_id'):f.append(OutboundOrder.id==p['order_id'])
    for param,field in {'id':'ob_no','pickup_location':'pickup_location','redirect_location':'redirect_code','del_ref':'reference_no','agent_code':'agent_code','delivery_type':'delivery_type'}.items():
        if p.get(param):f.append(getattr(OutboundOrder,field).ilike(f"%{p[param]}%"))
    if p.get('skd_pu_date'):f.append(func.date(OutboundOrder.schedule_pickup_at)==p['skd_pu_date'])
    if p.get('bol_no'):
        t=f"%{p['bol_no']}%";f.append(or_(OutboundOrder.bol_reference.ilike(t),OutboundOrder.id.in_(select(BOL.outbound_order_id).where(BOL.bol_no.ilike(t),BOL.status!=4))))
    if p.get('container_number'):f.append(OutboundOrder.allocations.any(OutboundInventoryAllocation.inventory_lot.has(InventoryLot.container_number.ilike(f"%{p['container_number']}%"))))
    if p.get('delivery_location'):
        t=f"%{p['delivery_location']}%";f.append(or_(OutboundOrder.fc_code.ilike(t),OutboundOrder.del_code.ilike(t)))
    if p.get('reference_search'):
        t=f"%{p['reference_search']}%";f.append(or_(OutboundOrder.reference_no.ilike(t),OutboundOrder.appointment_reference.ilike(t),FBAShipment.fba_no.ilike(t),FBAShipment.shipment_id.ilike(t),FBAShipment.po_number.ilike(t)))
    if p.get('q'):
        t=f"%{p['q']}%";f.append(or_(OutboundOrder.ob_no.ilike(t),OutboundOrder.reference_no.ilike(t),OutboundOrder.bol_reference.ilike(t),OutboundOrder.transfer_code.ilike(t),OutboundOrder.redirect_code.ilike(t),OutboundOrder.pickup_location.ilike(t),OutboundOrder.id.in_(select(BOL.outbound_order_id).where(BOL.bol_no.ilike(t),BOL.status!=4)),OutboundOrder.fc_code.ilike(t),OutboundOrder.del_code.ilike(t),FBAShipment.fba_no.ilike(t),FBAShipment.st_number.ilike(t),FBAShipment.po_number.ilike(t),OutboundOrder.allocations.any(OutboundInventoryAllocation.inventory_lot.has(InventoryLot.container_number.ilike(t)))))
    orders=db.scalars(q.where(*f)).unique().all();order_ids=[o.id for o in orders];pick_map={x[0]:x[1:] for x in db.execute(select(PickingList.outbound_order_id,func.coalesce(func.sum(PickingListItem.picked_pallet_qty),0),func.coalesce(func.sum(PickingListItem.picked_carton_qty),0),func.coalesce(func.sum(PickingListItem.picked_weight_lbs),0),func.coalesce(func.sum(PickingListItem.picked_cbm),0)).join(PickingListItem,PickingListItem.picking_list_id==PickingList.id).where(PickingList.outbound_order_id.in_(order_ids),PickingList.status!=PickingStatus.CANCELED).group_by(PickingList.outbound_order_id)).all()} if orders else {};delete_linked_ids=outbound_ids_with_delete_links(db,order_ids);rows=[]
    history_ids=history_job_ids(db)
    metadata=bol_metadata(db,orders,history_ids)
    for o in orders:
        alloc,complete,_=_numbers(o);pv=pick_map.get(o.id,(ZERO,ZERO,ZERO,ZERO));picked={'pallet_qty':pv[0],'carton_qty':pv[1],'weight_lbs':pv[2],'cbm':pv[3]};remain={x:alloc[x]-complete[x] for x in alloc};active={x:alloc[x]-complete[x] for x in alloc};writable=can_write(user) and o.import_job_id not in history_ids;readiness=get_dispatch_readiness(db,o);allowed={'confirm':writable and o.status in (OBStatus.NEW,OBStatus.IN_PROGRESS) and bool(o.allocations),'dispatch':False,'complete':writable and o.status==OBStatus.DISPATCHED,'cancel':writable and o.status in (OBStatus.NEW,OBStatus.HOLD,OBStatus.IN_PROGRESS,OBStatus.CONFIRMED),'delete':writable and o.status==OBStatus.NEW and o.load_id is None and o.id not in delete_linked_ids,'exception':writable and o.status not in (OBStatus.COMPLETED,OBStatus.CANCELED),'allocate':writable and o.status not in (OBStatus.DISPATCHED,OBStatus.COMPLETED,OBStatus.CANCELED),'release':writable and o.status not in (OBStatus.DISPATCHED,OBStatus.COMPLETED,OBStatus.CANCELED),'picking':writable and bool(o.allocations) and o.status not in (OBStatus.DISPATCHED,OBStatus.COMPLETED,OBStatus.CANCELED),'bol':writable and bool(o.allocations) and o.status not in (OBStatus.DISPATCHED,OBStatus.COMPLETED,OBStatus.CANCELED)}
        rows.append({'id':o.id,'dispatch_business_type':o.dispatch_business_type,'ob_no':o.ob_no,'status':o.status,'status_name':HISTORY_LABEL if o.import_job_id in history_ids else STATUS[o.status],'allowed_actions':allowed,'dispatch_readiness':readiness.status,'dispatch_checks':[check.model_dump(mode='json') for check in readiness.checks],'blocking_reasons':readiness.blocking_reasons,'customer':o.customer.customer_name if o.customer else None,'warehouse':o.warehouse.warehouse_code,'carrier':o.carrier.carrier_name if o.carrier else None,'loading_team':o.loading_team,'truck_type':o.truck_type,'delivery_type':o.delivery_type,'pickup_location':o.pickup_location,'schedule_pickup_at':o.schedule_pickup_at,'delivery_appointment_time':o.delivery_appointment_time,'ob_type':o.ob_type,'fba_id':o.fba_shipment_id,'fba_no':o.fba_shipment.fba_no if o.fba_shipment else None,'shipment_id':o.fba_shipment.shipment_id if o.fba_shipment else None,'st_number':o.fba_shipment.st_number if o.fba_shipment else None,'po_number':o.fba_shipment.po_number if o.fba_shipment else o.po_number,'fc_code':o.fc_code,'planned_pallet_qty':alloc['pallet_qty'],'allocated_pallet_qty':alloc['pallet_qty'],'picked_pallet_qty':picked['pallet_qty'],'completed_pallet_qty':complete['pallet_qty'],'remaining_pallet_qty':remain['pallet_qty'],'planned_carton_qty':alloc['carton_qty'],'allocated_carton_qty':alloc['carton_qty'],'picked_carton_qty':picked['carton_qty'],'completed_carton_qty':complete['carton_qty'],'remaining_carton_qty':remain['carton_qty'],'planned_weight_lbs':alloc['weight_lbs'],'allocated_weight_lbs':alloc['weight_lbs'],'picked_weight_lbs':picked['weight_lbs'],'completed_weight_lbs':complete['weight_lbs'],'remaining_weight_lbs':remain['weight_lbs'],'planned_cbm':alloc['cbm'],'allocated_cbm':alloc['cbm'],'picked_cbm':picked['cbm'],'completed_cbm':complete['cbm'],'remaining_cbm':remain['cbm'],'picking_count':sum(1 for x in pick_map if x==o.id),'bol_no':None,'reference_no':o.reference_no,'exception_reason':o.exception_reason,'created_at':o.created_at,'updated_at':o.updated_at})
        rows[-1].update({'warehouse_id':o.warehouse_id,'customer_id':o.customer_id,'fba_shipment_id':o.fba_shipment_id,'booked_pallet_qty':o.booked_pallet_qty,'appointment_reference':o.appointment_reference,'related_bols':o.related_bols,'remark':o.remark})
        rows[-1].update(metadata.get(o.id,{}))
    key=p.get('sort_by','created_at');rows.sort(key=lambda x:(x.get(key) is not None,x.get(key) or 0),reverse=p.get('sort_order','desc')!='asc');counts={str(k):sum(x['status']==k for x in rows) for k in range(8)};counts.update({'all':len(rows),'new':counts['0'],'hold':counts['1'],'in_progress':counts['2'],'confirmed':counts['3'],'dispatched':counts['4'],'completed':counts['5'],'canceled':counts['6'],'exception':counts['7']});page=p.get('page',1);per=p.get('per_page',20);summary={k:sum((x[k] for x in rows),ZERO) for k in ('allocated_pallet_qty','allocated_carton_qty','allocated_weight_lbs','allocated_cbm','completed_pallet_qty','remaining_pallet_qty')};summary['ob_count']=len(rows);summary['total_pallet_qty']=summary['allocated_pallet_qty'];return {'data':rows[(page-1)*per:page*per],'meta':{'page':page,'per_page':per,'total':len(rows),'total_pages':ceil(len(rows)/per) if rows else 0},'summary':summary,'status_counts':counts}
def detail(db:Session,ob_id:int,user:User):
    o=get_ob(db,ob_id,user=user);alloc=allocations(db,o);picks=list(db.scalars(select(PickingList).options(selectinload(PickingList.items)).where(PickingList.outbound_order_id==ob_id).order_by(PickingList.id.desc())).all());bols=list(db.scalars(select(BOL).options(selectinload(BOL.items)).where(BOL.outbound_order_id==ob_id).order_by(BOL.id.desc())).all());row=list_workbench(db,user,page=1,per_page=1,order_id=ob_id)['data'][0];sources=[]
    if o.ob_type=='FBA' and o.fba_shipment_id:
        fba_allocations=list(db.scalars(select(FBAInventoryAllocation).options(joinedload(FBAInventoryAllocation.inventory_lot).joinedload(InventoryLot.location)).where(FBAInventoryAllocation.fba_shipment_id==o.fba_shipment_id)).all())
        fba_ids=[a.id for a in fba_allocations]
        used_by_fba={x[0]:x[1:] for x in db.execute(select(OutboundInventoryAllocation.fba_allocation_id,func.coalesce(func.sum(OutboundInventoryAllocation.allocated_pallet_qty-OutboundInventoryAllocation.completed_pallet_qty),0),func.coalesce(func.sum(OutboundInventoryAllocation.allocated_carton_qty-OutboundInventoryAllocation.completed_carton_qty),0),func.coalesce(func.sum(OutboundInventoryAllocation.allocated_weight_lbs-OutboundInventoryAllocation.completed_weight_lbs),0),func.coalesce(func.sum(OutboundInventoryAllocation.allocated_cbm-OutboundInventoryAllocation.completed_cbm),0)).where(OutboundInventoryAllocation.fba_allocation_id.in_(fba_ids)).group_by(OutboundInventoryAllocation.fba_allocation_id)).all()} if fba_ids else {}
        for a in fba_allocations:
            used=used_by_fba.get(a.id,(ZERO,ZERO,ZERO,ZERO));remaining=(a.allocated_pallet_qty-used[0],a.allocated_carton_qty-used[1],a.allocated_weight_lbs-used[2],a.allocated_cbm-used[3])
            if any(value>ZERO for value in remaining):sources.append({'id':a.id,'inventory_lot_id':a.inventory_lot_id,'fba_allocation_id':a.id,'lot_no':a.inventory_lot.lot_no,'container_number':a.inventory_lot.container_number,'fc_code':a.inventory_lot.fc_code,'location':a.inventory_lot.location.location_code if a.inventory_lot.location else None,'remaining_pallet_qty':remaining[0],'remaining_carton_qty':remaining[1],'remaining_weight_lbs':remaining[2],'remaining_cbm':remaining[3],'source_type':'FBA','inbound_date':a.inventory_lot.inbound_date})
    else:
        for l in db.scalars(select(InventoryLot).options(joinedload(InventoryLot.location)).where(InventoryLot.warehouse_id==o.warehouse_id,InventoryLot.customer_id==o.customer_id,or_(InventoryLot.available_pallet_qty>0,InventoryLot.available_carton_qty>0,InventoryLot.available_weight_lbs>0,InventoryLot.available_cbm>0)).order_by(InventoryLot.inbound_date)).all():sources.append({'id':l.id,'inventory_lot_id':l.id,'lot_no':l.lot_no,'container_number':l.container_number,'fc_code':l.fc_code,'location':l.location.location_code if l.location else None,'available_pallet_qty':l.available_pallet_qty,'available_carton_qty':l.available_carton_qty,'available_weight_lbs':l.available_weight_lbs,'available_cbm':l.available_cbm,'source_type':'INVENTORY','inbound_date':l.inbound_date})
    if sources:
        aggregate=container_dispatch_aggregate(user);numbers={x['container_number'].upper() for x in sources};dispatch={cn.upper():dispatch_fields(earliest,inbound) for cn,earliest,inbound in db.execute(select(aggregate.c.container_number,aggregate.c.earliest_outbound_at,aggregate.c.inbound_date).where(func.upper(aggregate.c.container_number).in_(numbers))).all()}
        for source in sources:source.update(dispatch.get(source['container_number'].upper(),dispatch_fields(None,source.get('inbound_date'))))
        sources.sort(key=lambda x:(x['dispatch_priority_rank'],x['earliest_outbound_date'] or date.max,-(x['warehouse_days'] or 0)))
    return {'basic':row,'allocations':[x.model_dump(mode='json') for x in alloc],'picking':[picking_read(x).model_dump(mode='json') for x in picks],'bols':[bol_read(x).model_dump(mode='json') for x in bols],'remaining_sources':sources,'summary':{'allocated_pallet_qty':row['allocated_pallet_qty'],'completed_pallet_qty':row['completed_pallet_qty'],'remaining_pallet_qty':row['remaining_pallet_qty']},'workflow':[{'key':'allocation','label':'Allocated','status':'completed' if alloc else 'pending'},{'key':'picking','label':'Picking','status':'completed' if picks else 'pending'},{'key':'bol','label':'BOL','status':'completed' if bols else 'pending'},{'key':'dispatch','label':'Dispatch','status':'completed' if o.status in (OBStatus.DISPATCHED,OBStatus.COMPLETED) else 'pending'}],'audit':[],'allowed_actions':row['allowed_actions']}
