export type ColumnMapping=Record<string,string>
export interface ImportPreview{job_id:number;file_name:string;detected_columns:string[];suggested_mapping:ColumnMapping;preview_rows:Record<string,unknown>[];total_rows:number}
export interface WorkbookInspection{upload_token:string;file_name:string;file_size:number;file_hash:string;sheet_names:string[];sheet_row_estimates:Record<string,number>;west_coast_4_0_detected:boolean;suggested_profiles:Record<string,string>}
export interface ImportProfile{code:string;name:string;module:'INBOUND'|'FBA'|'OUTBOUND';sheet_name:string}
export interface ImportProgress{job_id:number;status:string;current_stage:string;processed_rows:number;total_rows:number;progress_percent:number;warning_rows:number;error_rows:number}
export interface ValidationIssue{severity:'WARNING'|'ERROR';column:string;code:string;message:string}export interface ValidationRow{row_number:number;data:Record<string,unknown>;status:'VALID'|'WARNING'|'ERROR';issues:ValidationIssue[]}
export interface ImportValidationResult{job_id:number;total_rows:number;valid_rows:number;warning_rows:number;error_rows:number;rows:ValidationRow[];duration_seconds?:number;rows_per_second?:number}
export interface ImportSummary{job_id:number;total_rows:number;imported_rows:number;skipped_rows:number;warning_rows:number;error_rows:number;reconciliation?:Record<string,unknown>}
export interface ImportJob{id:number;module:string;file_name:string;original_file_name:string;status:string;status_name:string;total_rows:number;processed_rows:number;progress_percent:number;current_stage:string;valid_rows:number;warning_rows:number;error_rows:number;imported_rows:number;created_by:number;created_at:string;completed_at:string|null;mapping:ColumnMapping|null;profile_code:string|null;source_sheet:string|null;performance?:Record<string,unknown>;reconciliation?:Record<string,unknown>}
export interface ImportError{id:number;row_number:number;column_name:string|null;raw_value:string|null;severity:'WARNING'|'ERROR';error_code:string;error_message:string;suggested_fix:string|null;created_at:string}export interface ImportRow{id:number;row_number:number;raw_data:Record<string,unknown>;mapped_data:Record<string,unknown>|null;validation_status:string;created_entity_type:string|null;created_entity_id:number|null;created_at:string}
