package com.dlxyuki.wms.outbound;

import com.dlxyuki.wms.user.UserAccount;
import java.math.*; import java.sql.*; import java.time.*; import java.util.*;
import org.springframework.jdbc.core.namedparam.*; import org.springframework.stereotype.Repository;

@Repository public class OutboundRepository {
 private final NamedParameterJdbcTemplate jdbc; public OutboundRepository(NamedParameterJdbcTemplate j){jdbc=j;}
 private static final String BASE="""
  with ag as (select outbound_order_id,count(*) allocation_count,coalesce(sum(allocated_pallet_qty),0) ap,coalesce(sum(allocated_carton_qty),0) ac,coalesce(sum(allocated_weight_lbs),0) aw,coalesce(sum(allocated_cbm),0) av,coalesce(sum(completed_pallet_qty),0) cp,coalesce(sum(completed_carton_qty),0) cc,coalesce(sum(completed_weight_lbs),0) cw,coalesce(sum(completed_cbm),0) cv from outbound_inventory_allocations group by outbound_order_id),
  pg as (select p.outbound_order_id,count(distinct p.id) picking_count,coalesce(sum(i.picked_pallet_qty),0) pp,coalesce(sum(i.picked_carton_qty),0) pc,coalesce(sum(i.picked_weight_lbs),0) pw,coalesce(sum(i.picked_cbm),0) pv from picking_lists p left join picking_list_items i on i.picking_list_id=p.id where p.status<>4 group by p.outbound_order_id)
  select o.*,c.customer_code,c.customer_name,w.warehouse_code,w.warehouse_name,cr.carrier_code,cr.carrier_name,f.fba_no,f.amazon_fc_code fba_fc,f.shipment_id,f.st_number,f.po_number fba_po,
   coalesce(ag.allocation_count,0) allocation_count,coalesce(ag.ap,0) ap,coalesce(ag.ac,0) ac,coalesce(ag.aw,0) aw,coalesce(ag.av,0) av,coalesce(ag.cp,0) cp,coalesce(ag.cc,0) cc,coalesce(ag.cw,0) cw,coalesce(ag.cv,0) cv,
   coalesce(pg.picking_count,0) picking_count,coalesce(pg.pp,0) pp,coalesce(pg.pc,0) pc,coalesce(pg.pw,0) pw,coalesce(pg.pv,0) pv
  from outbound_orders o left join customers c on c.id=o.customer_id join warehouses w on w.id=o.warehouse_id left join carriers cr on cr.id=o.carrier_id left join fba_shipments f on f.id=o.fba_shipment_id left join ag on ag.outbound_order_id=o.id left join pg on pg.outbound_order_id=o.id
  """;
 Object list(OutboundQuery q,UserAccount u){MapSqlParameterSource p=new MapSqlParameterSource();List<String> c=new ArrayList<>();scope(u,p,c); exact(c,p,"status",q.status(),"o.status");exact(c,p,"customer_id",q.customerId(),"o.customer_id");exact(c,p,"warehouse_id",q.warehouseId(),"o.warehouse_id");exact(c,p,"carrier_id",q.carrierId(),"o.carrier_id");exact(c,p,"fba_id",q.fbaShipmentId(),"o.fba_shipment_id");like(c,p,"ob_no",q.obNo(),"o.ob_no");like(c,p,"ob_type",q.obType(),"o.ob_type");like(c,p,"fc_code",q.fcCode(),"o.fc_code");like(c,p,"del_code",q.delCode(),"o.del_code");like(c,p,"agent_code",q.agentCode(),"o.agent_code");search(c,p,q.q(),false);List<Map<String,Object>> rows=jdbc.query(BASE+where(c),p,(r,n)->record(r));sort(rows,q.sortBy(),q.sortOrder());return page(rows,q.page(),q.perPage());}
 Object workbench(WorkbenchQuery q,UserAccount u){MapSqlParameterSource p=new MapSqlParameterSource();List<String> c=new ArrayList<>();scope(u,p,c);exact(c,p,"status",q.status(),"o.status");exact(c,p,"warehouse_id",q.warehouseId(),"o.warehouse_id");exact(c,p,"carrier_id",q.carrierId(),"o.carrier_id");exact(c,p,"ob_type",q.obType(),"o.ob_type");search(c,p,q.q(),true);List<Map<String,Object>> rows=jdbc.query(BASE+where(c),p,(r,n)->workbenchRow(r,u));sort(rows,q.sortBy(),q.sortOrder());Map<String,Integer> counts=new LinkedHashMap<>();for(int i=0;i<8;i++)counts.put(String.valueOf(i),0);for(var x:rows)counts.compute(String.valueOf(x.get("status")),(k,v)->v+1);counts.put("all",rows.size());String[] names={"new","hold","in_progress","confirmed","dispatched","completed","canceled","exception"};for(int i=0;i<8;i++)counts.put(names[i],counts.get(String.valueOf(i)));Map<String,Object> summary=new LinkedHashMap<>();for(String k:List.of("allocated_pallet_qty","allocated_carton_qty","allocated_weight_lbs","allocated_cbm","completed_pallet_qty","remaining_pallet_qty"))summary.put(k,sum(rows,k));summary.put("ob_count",rows.size());summary.put("total_pallet_qty",summary.get("allocated_pallet_qty"));Map<String,Object> out=new LinkedHashMap<>(page(rows,q.page(),q.perPage()));out.put("summary",summary);out.put("status_counts",counts);return out;}
 Optional<Map<String,Object>> find(long id,UserAccount u){MapSqlParameterSource p=new MapSqlParameterSource("id",id);List<String> c=new ArrayList<>(List.of("o.id=:id"));scope(u,p,c);return jdbc.query(BASE+where(c),p,(r,n)->record(r)).stream().findFirst();}
 List<Map<String,Object>> allocations(long id){String sql="""
  select a.*,i.lot_no,i.container_number,i.fc_code,i.location_id,l.location_code,l.location_name,o.fba_shipment_id,f.fba_no
  from outbound_inventory_allocations a join inventory_lots i on i.id=a.inventory_lot_id
  left join warehouse_locations l on l.id=i.location_id join outbound_orders o on o.id=a.outbound_order_id
  left join fba_shipments f on f.id=o.fba_shipment_id where a.outbound_order_id=:id order by a.id
  """;return jdbc.query(sql,Map.of("id",id),(r,n)->allocation(r));}
 Map<String,Object> readiness(long id){Map<String,Object> o=jdbc.queryForMap("select status,carrier_id,load_id from outbound_orders where id=:id",Map.of("id",id));if(o.get("load_id")!=null)return readinessResult(List.of(check("load_dispatch","Standalone dispatch",false,"Must dispatch through Load",null,"LOAD_DISPATCH_REQUIRED")),"DISPATCH_THROUGH_LOAD_REQUIRED");Map<String,Object> n=jdbc.queryForMap("""
  select count(a.id) filter(where a.allocated_pallet_qty>0) allocations,
  coalesce(sum(a.allocated_pallet_qty) filter(where a.allocated_pallet_qty>0),0) allocated,
  (select coalesce(sum(i.picked_pallet_qty),0) from picking_lists p join picking_list_items i on i.picking_list_id=p.id where p.outbound_order_id=:id and p.status<>4) picked,
  (select count(*) from bols where outbound_order_id=:id and status in(1,2,3) and length(trim(bol_no))>0) bols,
  (select count(*) from operational_exceptions where outbound_id=:id and status::text in('OPEN','INVESTIGATING')) exceptions
  from outbound_inventory_allocations a where a.outbound_order_id=:id
  """,Map.of("id",id));BigDecimal allocated=bd(n.get("allocated")),picked=bd(n.get("picked"));List<Map<String,Object>> checks=List.of(check("status","Confirmed status",((Number)o.get("status")).intValue()==3,"Outbound must be CONFIRMED before dispatch",null,"OUTBOUND_NOT_CONFIRMED"),check("allocation","Positive allocation",((Number)n.get("allocations")).longValue()>0&&allocated.signum()>0,"At least one positive pallet allocation is required","/outbound/picking","ALLOCATION_REQUIRED"),check("picking","Picking complete",allocated.signum()>0&&picked.compareTo(allocated)>=0,"Picking is incomplete: picked pallet quantity must cover allocated pallet quantity","/outbound/picking","PICKING_INCOMPLETE"),check("bol","Generated BOL",((Number)n.get("bols")).longValue()>0,"At least one generated BOL is required","/outbound/bol","SYSTEM_BOL_REQUIRED"),check("carrier","Carrier assigned",o.get("carrier_id")!=null,"Carrier is required before dispatch",null,"CARRIER_REQUIRED"),check("exceptions","No active exception",((Number)n.get("exceptions")).longValue()==0,"Resolve active outbound exceptions before dispatch","/trouble-shoot","ACTIVE_EXCEPTION"));return readinessResult(checks,null);}
 Object workbenchDetail(long id,UserAccount u){Map<String,Object> basic=jdbc.query(BASE+" where o.id=:id",Map.of("id",id),(r,n)->workbenchRow(r,u)).get(0);List<Map<String,Object>> a=allocations(id);List<Map<String,Object>> picks=rows("select * from picking_lists where outbound_order_id=:id order by id desc",id);List<Map<String,Object>> bols=rows("select * from bols where outbound_order_id=:id order by id desc",id);List<Map<String,Object>> sources=remainingSources(id,(String)basic.get("ob_type"),(Long)basic.get("fba_id"),((Number)basic.get("warehouse_id")).longValue());Map<String,Object> summary=new LinkedHashMap<>();for(String k:List.of("allocated_pallet_qty","completed_pallet_qty","remaining_pallet_qty"))summary.put(k,basic.get(k));List<Map<String,Object>> workflow=List.of(step("allocation","Allocated",!a.isEmpty()),step("picking","Picking",!picks.isEmpty()),step("bol","BOL",!bols.isEmpty()),step("dispatch","Dispatch",((Number)basic.get("status")).intValue()>=4));Map<String,Object> out=new LinkedHashMap<>();out.put("basic",basic);out.put("allocations",a);out.put("picking",picks);out.put("bols",bols);out.put("remaining_sources",sources);out.put("summary",summary);out.put("workflow",workflow);out.put("audit",List.of());out.put("allowed_actions",basic.get("allowed_actions"));return out;}
 private Map<String,Object> record(ResultSet r)throws SQLException{Map<String,Object>x=base(r);Long cid=nlong(r,"customer_id"),cr=nlong(r,"carrier_id"),fid=nlong(r,"fba_shipment_id");x.put("customer",cid==null?null:ref(cid,r.getString("customer_code"),r.getString("customer_name")));x.put("warehouse",ref(r.getLong("warehouse_id"),r.getString("warehouse_code"),r.getString("warehouse_name")));x.put("carrier",cr==null?null:ref(cr,r.getString("carrier_code"),r.getString("carrier_name")));x.put("fba_shipment",fid==null?null:ref(fid,r.getString("fba_no"),r.getString("fba_fc")));x.put("total_pallet_qty",dec(r,"ap"));x.put("total_carton_qty",dec(r,"ac"));x.put("total_weight_lbs",dec(r,"aw"));x.put("total_cbm",dec(r,"av"));x.put("allocation_count",r.getInt("allocation_count"));x.put("remaining_pallet_qty",sub(r,"ap","cp"));x.put("remaining_carton_qty",sub(r,"ac","cc"));return x;}
 private Map<String,Object> base(ResultSet r)throws SQLException{Map<String,Object>x=new LinkedHashMap<>();x.put("id",r.getLong("id"));x.put("ob_no",r.getString("ob_no"));int s=r.getInt("status");x.put("status",s);x.put("status_name",statusName(s));for(String k:List.of("ob_type","loading_team","truck_type","delivery_type","pickup_location","fc_code","del_code","agent_code","driver_name","truck_number","trailer_number","reference_no","exception_reason","remark"))x.put(k,r.getString(k));x.put("notify_carrier",r.getBoolean("notify_carrier"));x.put("schedule_pickup_at",time(r,"schedule_pickup_at"));x.put("delivery_appointment_time",time(r,"delivery_appointment_time"));x.put("created_at",time(r,"created_at"));x.put("updated_at",time(r,"updated_at"));return x;}
 private Map<String,Object> workbenchRow(ResultSet r,UserAccount u)throws SQLException{Map<String,Object>x=base(r);x.put("customer",r.getString("customer_name"));x.put("warehouse",r.getString("warehouse_code"));x.put("warehouse_id",r.getLong("warehouse_id"));x.put("carrier",r.getString("carrier_name"));x.put("fba_id",nlong(r,"fba_shipment_id"));for(String k:List.of("fba_no","shipment_id","st_number"))x.put(k,r.getString(k));x.put("po_number",r.getString("fba_po")!=null?r.getString("fba_po"):r.getString("po_number"));String[] qs={"pallet_qty","carton_qty","weight_lbs","cbm"};String[] cols={"ap","ac","aw","av"},done={"cp","cc","cw","cv"},picked={"pp","pc","pw","pv"};for(int i=0;i<4;i++){x.put("planned_"+qs[i],dec(r,cols[i]));x.put("allocated_"+qs[i],dec(r,cols[i]));x.put("picked_"+qs[i],dec(r,picked[i]));x.put("completed_"+qs[i],dec(r,done[i]));x.put("remaining_"+qs[i],sub(r,cols[i],done[i]));}x.put("picking_count",r.getInt("picking_count"));x.put("bol_no",null);Map<String,Object> ready=readiness(r.getLong("id"));x.put("dispatch_readiness",ready.get("status"));x.put("dispatch_checks",ready.get("checks"));x.put("blocking_reasons",ready.get("blocking_reasons"));x.put("allowed_actions",actions(r,u,"READY".equals(ready.get("status"))));return x;}
 private Map<String,Object> actions(ResultSet r,UserAccount u,boolean ready)throws SQLException{boolean w=Set.of("ADMIN","MANAGER","OUTBOUND","WAREHOUSE").contains(u.role());int s=r.getInt("status");boolean has=r.getInt("allocation_count")>0;Map<String,Object>x=new LinkedHashMap<>();x.put("confirm",w&&(s==0||s==2)&&has);x.put("dispatch",w&&ready);x.put("complete",w&&s==4);x.put("cancel",w&&Set.of(0,1,2,3).contains(s));x.put("exception",w&&s!=5&&s!=6);x.put("allocate",w&&s!=4&&s!=5&&s!=6);x.put("release",w&&s!=4&&s!=5&&s!=6);x.put("picking",w&&has&&s!=5&&s!=6);x.put("bol",w&&has&&s!=5&&s!=6);return x;}
 private List<Map<String,Object>> remainingSources(long id,String type,Long fbaId,long wh){if("FBA".equals(type)&&fbaId!=null)return jdbc.query("select a.id,a.id fba_allocation_id,i.lot_no,i.container_number,i.fc_code,l.location_code location,a.allocated_pallet_qty remaining_pallet_qty,a.allocated_carton_qty remaining_carton_qty,i.inbound_date from fba_inventory_allocations a join inventory_lots i on i.id=a.inventory_lot_id left join warehouse_locations l on l.id=i.location_id where a.fba_shipment_id=:x",Map.of("x",fbaId),(r,n)->rowMap(r,"FBA"));return jdbc.query("select i.id,i.id inventory_lot_id,i.lot_no,i.container_number,i.fc_code,l.location_code location,i.available_pallet_qty,i.available_carton_qty,i.inbound_date from inventory_lots i left join warehouse_locations l on l.id=i.location_id where i.warehouse_id=:x and i.available_pallet_qty>0 order by i.inbound_date",Map.of("x",wh),(r,n)->rowMap(r,"INVENTORY"));}
 private Map<String,Object> rowMap(ResultSet r,String source)throws SQLException{Map<String,Object>x=rowMap(r);x.put("source_type",source);return x;}private List<Map<String,Object>> rows(String sql,long id){return jdbc.query(sql,Map.of("id",id),(r,n)->rowMap(r));}
 private Map<String,Object> rowMap(ResultSet r)throws SQLException{Map<String,Object>x=new LinkedHashMap<>();ResultSetMetaData m=r.getMetaData();for(int i=1;i<=m.getColumnCount();i++){Object v=r.getObject(i);if(v instanceof BigDecimal d)v=d.toPlainString();if(v instanceof Timestamp t)v=t.toInstant().atOffset(ZoneOffset.UTC);x.put(m.getColumnLabel(i),v);}return x;}
 private Map<String,Object> allocation(ResultSet r)throws SQLException{Map<String,Object>x=new LinkedHashMap<>();x.put("id",r.getLong("id"));x.put("inventory_lot_id",r.getLong("inventory_lot_id"));x.put("fba_allocation_id",nlong(r,"fba_allocation_id"));for(String k:List.of("lot_no","container_number","fc_code"))x.put(k,r.getString(k));Long lid=nlong(r,"location_id");x.put("location",lid==null?null:ref(lid,r.getString("location_code"),r.getString("location_name")));for(String k:List.of("allocated_pallet_qty","allocated_carton_qty","allocated_weight_lbs","allocated_cbm","completed_pallet_qty","completed_carton_qty","completed_weight_lbs","completed_cbm"))x.put(k,dec(r,k));x.put("source_type",x.get("fba_allocation_id")!=null?"FBA":"INVENTORY");x.put("fba_no",r.getString("fba_no"));x.put("created_at",time(r,"created_at"));return x;}
 private Map<String,Object> readinessResult(List<Map<String,Object>> checks,String error){List<String> reasons=new ArrayList<>(),codes=new ArrayList<>();for(var c:checks)if(!((Boolean)c.get("passed"))){reasons.add((String)c.get("reason"));codes.add((String)c.get("code"));}Map<String,Object>x=new LinkedHashMap<>();x.put("status",reasons.isEmpty()?"READY":"NOT_READY");x.put("checks",checks);x.put("blocking_reasons",reasons);x.put("blocking_codes",codes);x.put("error_code",error);return x;}
 private Map<String,Object> check(String key,String label,boolean pass,String reason,String route,String code){Map<String,Object>x=new LinkedHashMap<>();x.put("key",key);x.put("label",label);x.put("passed",pass);x.put("reason",pass?null:reason);x.put("route",route);x.put("code",pass?null:code);return x;}private Map<String,Object> step(String key,String label,boolean done){return Map.of("key",key,"label",label,"status",done?"completed":"pending");}
 private Map<String,Object> page(List<Map<String,Object>> rows,int page,int size){int from=Math.min((page-1)*size,rows.size()),to=Math.min(from+size,rows.size());Map<String,Object>x=new LinkedHashMap<>();x.put("data",List.copyOf(rows.subList(from,to)));x.put("meta",Map.of("page",page,"per_page",size,"total",rows.size(),"total_pages",rows.isEmpty()?0:(rows.size()+size-1)/size));return x;}
 private void scope(UserAccount u,MapSqlParameterSource p,List<String>c){if(!"ADMIN".equals(u.role())&&"SELECTED".equals(u.warehouseScopeMode())){if(u.warehouseIds().isEmpty())c.add("false");else{p.addValue("scope_w",u.warehouseIds());c.add("o.warehouse_id in (:scope_w)");}}if(!"ADMIN".equals(u.role())&&"SELECTED".equals(u.customerScopeMode())){if(u.customerIds().isEmpty())c.add("false");else{p.addValue("scope_c",u.customerIds());c.add("o.customer_id in (:scope_c)");}}}
 private void search(List<String>c,MapSqlParameterSource p,String q,boolean wb){if(q==null)return;p.addValue("q","%"+q+"%");String s="(o.ob_no ilike :q or o.reference_no ilike :q or o.fc_code ilike :q or o.del_code ilike :q"+(wb?" or f.fba_no ilike :q or f.st_number ilike :q or f.po_number ilike :q or exists(select 1 from outbound_inventory_allocations ax join inventory_lots ix on ix.id=ax.inventory_lot_id where ax.outbound_order_id=o.id and ix.container_number ilike :q)":" or o.agent_code ilike :q or o.truck_number ilike :q or o.trailer_number ilike :q or o.driver_name ilike :q or o.remark ilike :q")+")";c.add(s);}private void exact(List<String>c,MapSqlParameterSource p,String k,Object v,String col){if(v!=null){p.addValue(k,v);c.add(col+"=:"+k);}}private void like(List<String>c,MapSqlParameterSource p,String k,String v,String col){if(v!=null){p.addValue(k,"%"+v+"%");c.add(col+" ilike :"+k);}}private String where(List<String>c){return c.isEmpty()?"":" where "+String.join(" and ",c);}
 @SuppressWarnings({"rawtypes","unchecked"})private void sort(List<Map<String,Object>>r,String k,String order){Set<String> ok=Set.of("id","created_at","updated_at","ob_no","status","schedule_pickup_at","delivery_appointment_time");if(!ok.contains(k))k="id";String key=k;Comparator<Map<String,Object>>c=(a,b)->{Object x=a.get(key),y=b.get(key);if(x==null)return y==null?0:-1;if(y==null)return 1;return x instanceof Comparable&&x.getClass()==y.getClass()?((Comparable)x).compareTo(y):x.toString().compareTo(y.toString());};if("desc".equals(order))c=c.reversed();r.sort(c.thenComparingLong(x->((Number)x.get("id")).longValue()));}
 private String sum(List<Map<String,Object>>r,String k){return r.stream().map(x->new BigDecimal((String)x.get(k))).reduce(BigDecimal.ZERO,BigDecimal::add).toPlainString();}private BigDecimal bd(Object x){return x instanceof BigDecimal b?b:new BigDecimal(x.toString());}private String dec(ResultSet r,String k)throws SQLException{return Optional.ofNullable(r.getBigDecimal(k)).orElse(BigDecimal.ZERO).toPlainString();}private String sub(ResultSet r,String a,String b)throws SQLException{return r.getBigDecimal(a).subtract(r.getBigDecimal(b)).toPlainString();}private Long nlong(ResultSet r,String k)throws SQLException{long v=r.getLong(k);return r.wasNull()?null:v;}private Object time(ResultSet r,String k)throws SQLException{Timestamp t=r.getTimestamp(k);return t==null?null:t.toInstant().atOffset(ZoneOffset.UTC);}private Map<String,Object> ref(long id,String code,String name){Map<String,Object>x=new LinkedHashMap<>();x.put("id",id);x.put("code",code);x.put("name",name);return x;}private String statusName(int s){return List.of("New","Hold","In Progress","Confirmed","Dispatched","Completed","Canceled","Exception").get(Math.max(0,Math.min(7,s)));}
}
