"""phase 2 inbound and import framework

Revision ID: 20260828_0002
Revises: 20260828_0001
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="20260828_0002";down_revision="20260828_0001";branch_labels=None;depends_on=None
import_module=postgresql.ENUM("INBOUND","FBA","OUTBOUND","INVENTORY_ADJUSTMENT",name="import_module",create_type=False)
import_status=postgresql.ENUM("UPLOADED","PREVIEWED","VALIDATED","IMPORTING","COMPLETED","FAILED","CANCELED",name="import_status",create_type=False)
import_severity=postgresql.ENUM("WARNING","ERROR",name="import_severity",create_type=False)
row_status=postgresql.ENUM("PENDING","VALID","WARNING","ERROR","IMPORTED","SKIPPED",name="row_validation_status",create_type=False)
def upgrade()->None:
    bind=op.get_bind()
    for enum in (import_module,import_status,import_severity,row_status):enum.create(bind,checkfirst=True)
    op.create_table("import_jobs",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("module",import_module,nullable=False),sa.Column("file_name",sa.String(255),nullable=False),sa.Column("original_file_name",sa.String(255),nullable=False),sa.Column("status",import_status,nullable=False),sa.Column("total_rows",sa.Integer(),nullable=False),sa.Column("valid_rows",sa.Integer(),nullable=False),sa.Column("warning_rows",sa.Integer(),nullable=False),sa.Column("error_rows",sa.Integer(),nullable=False),sa.Column("imported_rows",sa.Integer(),nullable=False),sa.Column("mapping",postgresql.JSONB()),sa.Column("created_by",sa.Integer(),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)));op.create_index("ix_import_jobs_module","import_jobs",["module"]);op.create_index("ix_import_jobs_status","import_jobs",["status"]);op.create_index("ix_import_jobs_created_by","import_jobs",["created_by"])
    op.create_table("import_rows",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("import_job_id",sa.Integer(),sa.ForeignKey("import_jobs.id",ondelete="CASCADE"),nullable=False),sa.Column("row_number",sa.Integer(),nullable=False),sa.Column("raw_data",postgresql.JSONB(),nullable=False),sa.Column("mapped_data",postgresql.JSONB()),sa.Column("validation_status",row_status,nullable=False),sa.Column("created_entity_type",sa.String(50)),sa.Column("created_entity_id",sa.Integer()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_import_rows_import_job_id","import_rows",["import_job_id"])
    op.create_table("import_errors",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("import_job_id",sa.Integer(),sa.ForeignKey("import_jobs.id",ondelete="CASCADE"),nullable=False),sa.Column("row_number",sa.Integer(),nullable=False),sa.Column("column_name",sa.String(100)),sa.Column("raw_value",sa.Text()),sa.Column("severity",import_severity,nullable=False),sa.Column("error_code",sa.String(50),nullable=False),sa.Column("error_message",sa.Text(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False));op.create_index("ix_import_errors_import_job_id","import_errors",["import_job_id"])
    op.create_table("inbound_records",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("inbound_no",sa.String(20),nullable=False),sa.Column("container_number",sa.String(50),nullable=False),sa.Column("customer_id",sa.Integer(),sa.ForeignKey("customers.id",ondelete="RESTRICT")),sa.Column("warehouse_id",sa.Integer(),sa.ForeignKey("warehouses.id",ondelete="RESTRICT"),nullable=False),sa.Column("unload_date",sa.Date()),sa.Column("received_date",sa.Date()),sa.Column("fc_code",sa.String(20)),sa.Column("marking",sa.String(100)),sa.Column("pallet_qty",sa.Numeric(12,2),nullable=False),sa.Column("carton_qty",sa.Numeric(12,2),nullable=False),sa.Column("weight_lbs",sa.Numeric(14,2)),sa.Column("cbm",sa.Numeric(14,4)),sa.Column("location_id",sa.Integer(),sa.ForeignKey("warehouse_locations.id",ondelete="RESTRICT")),sa.Column("status",sa.SmallInteger(),nullable=False),sa.Column("remark",sa.Text()),sa.Column("import_job_id",sa.Integer(),sa.ForeignKey("import_jobs.id",ondelete="SET NULL")),sa.Column("created_by",sa.Integer(),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.CheckConstraint("pallet_qty >= 0",name="ck_inbound_records_pallet_non_negative"),sa.CheckConstraint("carton_qty >= 0",name="ck_inbound_records_carton_non_negative"),sa.CheckConstraint("weight_lbs IS NULL OR weight_lbs >= 0",name="ck_inbound_records_weight_non_negative"),sa.CheckConstraint("cbm IS NULL OR cbm >= 0",name="ck_inbound_records_cbm_non_negative"),sa.CheckConstraint("status BETWEEN 0 AND 5",name="ck_inbound_records_status_range"));op.create_index("ix_inbound_records_inbound_no","inbound_records",["inbound_no"],unique=True)
    for col in ("container_number","customer_id","warehouse_id","fc_code","marking","location_id","status","import_job_id","created_by"):op.create_index(f"ix_inbound_records_{col}","inbound_records",[col])
    op.create_table("audit_logs",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("action",sa.String(30),nullable=False),sa.Column("entity_type",sa.String(50),nullable=False),sa.Column("entity_id",sa.Integer()),sa.Column("before_data",postgresql.JSONB()),sa.Column("after_data",postgresql.JSONB()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    for col in ("user_id","action","entity_type","entity_id"):op.create_index(f"ix_audit_logs_{col}","audit_logs",[col])
def downgrade()->None:
    for table in ("audit_logs","inbound_records","import_errors","import_rows","import_jobs"):op.drop_table(table)
    bind=op.get_bind()
    for enum in (row_status,import_severity,import_status,import_module):enum.drop(bind,checkfirst=True)
