"""phase 10.2 warehouse work order foundation"""
from alembic import op
import sqlalchemy as sa
revision='20260829_0014';down_revision='20260829_0013';branch_labels=None;depends_on=None
def upgrade():
 op.create_table('work_orders',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('work_order_no',sa.String(32),nullable=False),sa.Column('work_order_type',sa.Enum('PICK','STAGE','LOAD','CHECK','GENERAL',name='work_order_type'),nullable=False),sa.Column('status',sa.Enum('OPEN','ASSIGNED','IN_PROGRESS','COMPLETED','CANCELED',name='work_order_status'),nullable=False),sa.Column('warehouse_id',sa.Integer(),sa.ForeignKey('warehouses.id',ondelete='RESTRICT'),nullable=False),sa.Column('load_id',sa.Integer(),sa.ForeignKey('loads.id',ondelete='SET NULL')),sa.Column('outbound_id',sa.Integer(),sa.ForeignKey('outbound_orders.id',ondelete='SET NULL')),sa.Column('picking_list_id',sa.Integer(),sa.ForeignKey('picking_lists.id',ondelete='SET NULL')),sa.Column('container_tracking_id',sa.Integer(),sa.ForeignKey('container_trackings.id',ondelete='SET NULL')),sa.Column('priority',sa.Enum('LOW','NORMAL','HIGH','URGENT',name='work_order_priority'),nullable=False),sa.Column('assigned_to',sa.Integer(),sa.ForeignKey('users.id',ondelete='SET NULL')),sa.Column('assigned_team',sa.String(100)),sa.Column('scheduled_at',sa.DateTime(timezone=True)),sa.Column('started_at',sa.DateTime(timezone=True)),sa.Column('completed_at',sa.DateTime(timezone=True)),sa.Column('notes',sa.Text()),sa.Column('created_by',sa.Integer(),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
 for name,col in [('ix_work_orders_work_order_no','work_order_no'),('ix_work_orders_work_order_type','work_order_type'),('ix_work_orders_status','status'),('ix_work_orders_warehouse_id','warehouse_id'),('ix_work_orders_load_id','load_id'),('ix_work_orders_outbound_id','outbound_id'),('ix_work_orders_picking_list_id','picking_list_id'),('ix_work_orders_container_tracking_id','container_tracking_id'),('ix_work_orders_priority','priority'),('ix_work_orders_assigned_to','assigned_to'),('ix_work_orders_created_by','created_by')]:op.create_index(name,'work_orders',[col],unique=name.endswith('work_order_no'))
 op.create_index('ix_work_orders_warehouse_status','work_orders',['warehouse_id','status'])
def downgrade():
 op.drop_table('work_orders');op.execute('DROP TYPE IF EXISTS work_order_priority');op.execute('DROP TYPE IF EXISTS work_order_status');op.execute('DROP TYPE IF EXISTS work_order_type')
