"""phase 4 fba

Revision ID: 20260828_0004
Revises: 20260828_0003
"""
from alembic import op
import sqlalchemy as sa
revision="20260828_0004";down_revision="20260828_0003";branch_labels=None;depends_on=None
def upgrade()->None:
    op.create_table("fba_shipments",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("fba_no",sa.String(24),nullable=False),sa.Column("customer_id",sa.Integer(),sa.ForeignKey("customers.id",ondelete="RESTRICT")),sa.Column("warehouse_id",sa.Integer(),sa.ForeignKey("warehouses.id",ondelete="RESTRICT"),nullable=False),sa.Column("amazon_fc_code",sa.String(20),nullable=False),sa.Column("amazon_fc_address_id",sa.Integer(),sa.ForeignKey("amazon_fc_addresses.id",ondelete="SET NULL")),sa.Column("status",sa.SmallInteger(),nullable=False),sa.Column("scheduled_pickup_at",sa.DateTime(timezone=True)),sa.Column("appointment_time",sa.DateTime(timezone=True)),sa.Column("carrier_id",sa.Integer(),sa.ForeignKey("carriers.id",ondelete="RESTRICT")),sa.Column("reference_no",sa.String(100)),sa.Column("shipment_id",sa.String(100)),sa.Column("st_number",sa.String(100)),sa.Column("remark",sa.Text()),sa.Column("created_by",sa.Integer(),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("fba_no",name="uq_fba_shipments_fba_no"),sa.CheckConstraint("status BETWEEN 0 AND 9",name="ck_fba_shipments_status_range"))
    for col in ("fba_no","customer_id","warehouse_id","amazon_fc_code","amazon_fc_address_id","carrier_id","status","appointment_time","created_at"):op.create_index(f"ix_fba_shipments_{col}","fba_shipments",[col],unique=col=="fba_no")
    op.create_table("fba_inventory_allocations",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("fba_shipment_id",sa.Integer(),sa.ForeignKey("fba_shipments.id",ondelete="CASCADE"),nullable=False),sa.Column("inventory_lot_id",sa.Integer(),sa.ForeignKey("inventory_lots.id",ondelete="RESTRICT"),nullable=False),sa.Column("allocated_pallet_qty",sa.Numeric(12,2),nullable=False),sa.Column("allocated_carton_qty",sa.Numeric(12,2),nullable=False),sa.Column("allocated_weight_lbs",sa.Numeric(14,2),nullable=False),sa.Column("allocated_cbm",sa.Numeric(14,4),nullable=False),sa.Column("created_by",sa.Integer(),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("fba_shipment_id","inventory_lot_id",name="uq_fba_lot_allocation"),sa.CheckConstraint("allocated_pallet_qty >= 0 AND allocated_carton_qty >= 0 AND allocated_weight_lbs >= 0 AND allocated_cbm >= 0",name="ck_fba_inventory_allocations_quantities_non_negative"));op.create_index("ix_fba_inventory_allocations_fba_shipment_id","fba_inventory_allocations",["fba_shipment_id"]);op.create_index("ix_fba_inventory_allocations_inventory_lot_id","fba_inventory_allocations",["inventory_lot_id"])
def downgrade()->None:op.drop_table("fba_inventory_allocations");op.drop_table("fba_shipments")
