"""phase 5 outbound
Revision ID: 20260828_0005
Revises: 20260828_0004
"""
from alembic import op
import sqlalchemy as sa
revision='20260828_0005';down_revision='20260828_0004';branch_labels=None;depends_on=None
def upgrade():
 op.create_table('outbound_orders',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('ob_no',sa.String(24),nullable=False),sa.Column('customer_id',sa.Integer()),sa.Column('warehouse_id',sa.Integer(),nullable=False),sa.Column('carrier_id',sa.Integer()),sa.Column('fba_shipment_id',sa.Integer()),sa.Column('status',sa.SmallInteger(),nullable=False,server_default='0'),sa.Column('loading_team',sa.String(100)),sa.Column('truck_type',sa.String(50)),sa.Column('notify_carrier',sa.Boolean(),nullable=False,server_default='false'),sa.Column('delivery_type',sa.String(50)),sa.Column('pickup_location',sa.String(255)),sa.Column('schedule_pickup_at',sa.DateTime(timezone=True)),sa.Column('delivery_appointment_time',sa.DateTime(timezone=True)),sa.Column('ob_type',sa.String(20),nullable=False,server_default='STANDARD'),sa.Column('fc_code',sa.String(20)),sa.Column('del_code',sa.String(50)),sa.Column('agent_code',sa.String(50)),sa.Column('driver_name',sa.String(100)),sa.Column('driver_phone',sa.String(50)),sa.Column('truck_number',sa.String(50)),sa.Column('trailer_number',sa.String(50)),sa.Column('reference_no',sa.String(100)),sa.Column('exception_reason',sa.Text()),sa.Column('remark',sa.Text()),sa.Column('created_by',sa.Integer(),nullable=False),sa.Column('confirmed_at',sa.DateTime(timezone=True)),sa.Column('confirmed_by',sa.Integer()),sa.Column('dispatched_at',sa.DateTime(timezone=True)),sa.Column('dispatched_by',sa.Integer()),sa.Column('completed_at',sa.DateTime(timezone=True)),sa.Column('completed_by',sa.Integer()),sa.Column('canceled_at',sa.DateTime(timezone=True)),sa.Column('canceled_by',sa.Integer()),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(['customer_id'],['customers.id'],ondelete='RESTRICT'),sa.ForeignKeyConstraint(['warehouse_id'],['warehouses.id'],ondelete='RESTRICT'),sa.ForeignKeyConstraint(['carrier_id'],['carriers.id'],ondelete='RESTRICT'),sa.ForeignKeyConstraint(['fba_shipment_id'],['fba_shipments.id'],ondelete='RESTRICT'),sa.ForeignKeyConstraint(['created_by'],['users.id'],ondelete='RESTRICT'),sa.ForeignKeyConstraint(['confirmed_by'],['users.id'],ondelete='RESTRICT'),sa.ForeignKeyConstraint(['dispatched_by'],['users.id'],ondelete='RESTRICT'),sa.ForeignKeyConstraint(['completed_by'],['users.id'],ondelete='RESTRICT'),sa.ForeignKeyConstraint(['canceled_by'],['users.id'],ondelete='RESTRICT'),sa.CheckConstraint('status BETWEEN 0 AND 7',name='status_range'))
 for col in ('ob_no','status','ob_type','customer_id','warehouse_id','carrier_id','fba_shipment_id','fc_code','del_code','agent_code','schedule_pickup_at','delivery_appointment_time','created_at'):op.create_index(f'ix_outbound_orders_{col}','outbound_orders',[col],unique=col=='ob_no')
 op.create_table('outbound_inventory_allocations',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('outbound_order_id',sa.Integer(),nullable=False),sa.Column('inventory_lot_id',sa.Integer(),nullable=False),sa.Column('fba_allocation_id',sa.Integer()),sa.Column('allocated_pallet_qty',sa.Numeric(12,2),nullable=False,server_default='0'),sa.Column('allocated_carton_qty',sa.Numeric(12,2),nullable=False,server_default='0'),sa.Column('allocated_weight_lbs',sa.Numeric(14,2),nullable=False,server_default='0'),sa.Column('allocated_cbm',sa.Numeric(14,4),nullable=False,server_default='0'),sa.Column('completed_pallet_qty',sa.Numeric(12,2),nullable=False,server_default='0'),sa.Column('completed_carton_qty',sa.Numeric(12,2),nullable=False,server_default='0'),sa.Column('completed_weight_lbs',sa.Numeric(14,2),nullable=False,server_default='0'),sa.Column('completed_cbm',sa.Numeric(14,4),nullable=False,server_default='0'),sa.Column('created_by',sa.Integer(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(['outbound_order_id'],['outbound_orders.id'],ondelete='CASCADE'),sa.ForeignKeyConstraint(['inventory_lot_id'],['inventory_lots.id'],ondelete='RESTRICT'),sa.ForeignKeyConstraint(['fba_allocation_id'],['fba_inventory_allocations.id'],ondelete='RESTRICT'),sa.ForeignKeyConstraint(['created_by'],['users.id'],ondelete='RESTRICT'),sa.UniqueConstraint('outbound_order_id','inventory_lot_id',name='uq_outbound_lot_allocation'),sa.CheckConstraint('allocated_pallet_qty >= 0 AND allocated_carton_qty >= 0 AND allocated_weight_lbs >= 0 AND allocated_cbm >= 0',name='quantities_non_negative'),sa.CheckConstraint('completed_pallet_qty >= 0 AND completed_carton_qty >= 0 AND completed_weight_lbs >= 0 AND completed_cbm >= 0',name='completed_non_negative'))
 for col in ('outbound_order_id','inventory_lot_id','fba_allocation_id'):op.create_index(f'ix_outbound_inventory_allocations_{col}','outbound_inventory_allocations',[col])
def downgrade():op.drop_table('outbound_inventory_allocations');op.drop_table('outbound_orders')
