"""phase 6 picking and BOL
Revision ID: 20260828_0006
Revises: 20260828_0005
"""
from alembic import op
import sqlalchemy as sa
revision='20260828_0006';down_revision='20260828_0005';branch_labels=None;depends_on=None
def upgrade():
 op.create_table('picking_lists',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('picking_no',sa.String(24),nullable=False),sa.Column('outbound_order_id',sa.Integer(),nullable=False),sa.Column('status',sa.SmallInteger(),nullable=False,server_default='0'),sa.Column('assigned_team',sa.String(100)),sa.Column('assigned_to',sa.Integer()),sa.Column('printed_at',sa.DateTime(timezone=True)),sa.Column('printed_by',sa.Integer()),sa.Column('started_at',sa.DateTime(timezone=True)),sa.Column('started_by',sa.Integer()),sa.Column('completed_at',sa.DateTime(timezone=True)),sa.Column('completed_by',sa.Integer()),sa.Column('canceled_at',sa.DateTime(timezone=True)),sa.Column('canceled_by',sa.Integer()),sa.Column('remark',sa.Text()),sa.Column('created_by',sa.Integer(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(['outbound_order_id'],['outbound_orders.id'],ondelete='RESTRICT'),sa.ForeignKeyConstraint(['created_by'],['users.id'],ondelete='RESTRICT'))
 op.create_index('ix_picking_lists_picking_no','picking_lists',['picking_no'],unique=True);op.create_index('ix_picking_lists_outbound_order_id','picking_lists',['outbound_order_id']);op.create_index('ix_picking_lists_status','picking_lists',['status'])
 op.create_table('picking_list_items',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('picking_list_id',sa.Integer(),nullable=False),sa.Column('outbound_allocation_id',sa.Integer(),nullable=False),sa.Column('inventory_lot_id',sa.Integer(),nullable=False),sa.Column('location_id',sa.Integer()),sa.Column('lot_no',sa.String(24),nullable=False),sa.Column('container_number',sa.String(50),nullable=False),sa.Column('fc_code',sa.String(20)),sa.Column('marking',sa.String(100)),sa.Column('planned_pallet_qty',sa.Numeric(12,2),nullable=False,server_default='0'),sa.Column('planned_carton_qty',sa.Numeric(12,2),nullable=False,server_default='0'),sa.Column('planned_weight_lbs',sa.Numeric(14,2),nullable=False,server_default='0'),sa.Column('planned_cbm',sa.Numeric(14,4),nullable=False,server_default='0'),sa.Column('picked_pallet_qty',sa.Numeric(12,2),nullable=False,server_default='0'),sa.Column('picked_carton_qty',sa.Numeric(12,2),nullable=False,server_default='0'),sa.Column('picked_weight_lbs',sa.Numeric(14,2),nullable=False,server_default='0'),sa.Column('picked_cbm',sa.Numeric(14,4),nullable=False,server_default='0'),sa.Column('sequence_no',sa.SmallInteger(),nullable=False,server_default='1'),sa.Column('remark',sa.Text()),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(['picking_list_id'],['picking_lists.id'],ondelete='CASCADE'),sa.ForeignKeyConstraint(['outbound_allocation_id'],['outbound_inventory_allocations.id'],ondelete='RESTRICT'),sa.ForeignKeyConstraint(['inventory_lot_id'],['inventory_lots.id'],ondelete='RESTRICT'),sa.ForeignKeyConstraint(['location_id'],['warehouse_locations.id'],ondelete='RESTRICT'))
 for c in ('picking_list_id','outbound_allocation_id','inventory_lot_id','location_id'):op.create_index('ix_picking_list_items_'+c,'picking_list_items',[c])
 op.create_table('bols',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('bol_no',sa.String(24),nullable=False),sa.Column('outbound_order_id',sa.Integer(),nullable=False),sa.Column('fba_shipment_id',sa.Integer()),sa.Column('customer_id',sa.Integer()),sa.Column('warehouse_id',sa.Integer(),nullable=False),sa.Column('carrier_id',sa.Integer()),sa.Column('ship_from_name',sa.String(200),nullable=False),sa.Column('ship_from_address',sa.Text(),nullable=False),sa.Column('ship_to_name',sa.String(200)),sa.Column('ship_to_address',sa.Text()),sa.Column('amazon_fc_code',sa.String(20)),sa.Column('pickup_date',sa.Date()),sa.Column('appointment_time',sa.String(40)),sa.Column('status',sa.SmallInteger(),nullable=False,server_default='0'),sa.Column('special_instructions',sa.Text()),sa.Column('created_by',sa.Integer(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(['outbound_order_id'],['outbound_orders.id'],ondelete='RESTRICT'),sa.ForeignKeyConstraint(['fba_shipment_id'],['fba_shipments.id'],ondelete='SET NULL'),sa.ForeignKeyConstraint(['warehouse_id'],['warehouses.id'],ondelete='RESTRICT'),sa.ForeignKeyConstraint(['created_by'],['users.id'],ondelete='RESTRICT'))
 op.create_index('ix_bols_bol_no','bols',['bol_no'],unique=True);op.create_index('ix_bols_outbound_order_id','bols',['outbound_order_id']);op.create_index('ix_bols_status','bols',['status'])
 op.create_table('bol_items',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('bol_id',sa.Integer(),nullable=False),sa.Column('outbound_allocation_id',sa.Integer(),nullable=False),sa.Column('inventory_lot_id',sa.Integer(),nullable=False),sa.Column('container_number',sa.String(50)),sa.Column('fc_code',sa.String(20)),sa.Column('marking',sa.String(100)),sa.Column('pallet_qty',sa.Numeric(12,2),nullable=False,server_default='0'),sa.Column('carton_qty',sa.Numeric(12,2),nullable=False,server_default='0'),sa.Column('weight_lbs',sa.Numeric(14,2),nullable=False,server_default='0'),sa.Column('cbm',sa.Numeric(14,4),nullable=False,server_default='0'),sa.Column('description',sa.Text()),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(['bol_id'],['bols.id'],ondelete='CASCADE'),sa.ForeignKeyConstraint(['outbound_allocation_id'],['outbound_inventory_allocations.id'],ondelete='RESTRICT'),sa.ForeignKeyConstraint(['inventory_lot_id'],['inventory_lots.id'],ondelete='RESTRICT'))
 op.create_index('ix_bol_items_bol_id','bol_items',['bol_id']);op.create_index('ix_bol_items_outbound_allocation_id','bol_items',['outbound_allocation_id']);op.create_index('ix_bol_items_inventory_lot_id','bol_items',['inventory_lot_id'])
def downgrade():op.drop_table('bol_items');op.drop_table('bols');op.drop_table('picking_list_items');op.drop_table('picking_lists')
