"""phase 7 schema alignment

Revision ID: e852423c687a
Revises: 20260828_0006
Create Date: 2026-08-27 16:10:21.216446
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision: str = 'e852423c687a'
down_revision: Union[str, None] = '20260828_0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bol_items', 'created_at')
    op.create_index(op.f('ix_bols_fba_shipment_id'), 'bols', ['fba_shipment_id'], unique=False)
    op.create_foreign_key(op.f('fk_bols_customer_id_customers'), 'bols', 'customers', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_bols_carrier_id_carriers'), 'bols', 'carriers', ['carrier_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_fba_shipments_created_at'), table_name='fba_shipments')
    op.drop_constraint(op.f('uq_fba_shipments_fba_no'), 'fba_shipments', type_='unique')
    op.create_index(op.f('ix_fba_shipments_reference_no'), 'fba_shipments', ['reference_no'], unique=False)
    op.create_index(op.f('ix_fba_shipments_shipment_id'), 'fba_shipments', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_fba_shipments_st_number'), 'fba_shipments', ['st_number'], unique=False)
    op.drop_constraint(op.f('uq_inventory_lots_lot_no'), 'inventory_lots', type_='unique')
    op.drop_constraint(op.f('uq_inventory_lots_source_inbound_id'), 'inventory_lots', type_='unique')
    op.drop_index(op.f('ix_inventory_transactions_reference'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_outbound_orders_created_at'), table_name='outbound_orders')
    op.drop_index(op.f('ix_outbound_orders_ob_type'), table_name='outbound_orders')
    op.create_index(op.f('ix_outbound_orders_reference_no'), 'outbound_orders', ['reference_no'], unique=False)
    op.create_foreign_key(op.f('fk_picking_lists_printed_by_users'), 'picking_lists', 'users', ['printed_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_picking_lists_assigned_to_users'), 'picking_lists', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_picking_lists_completed_by_users'), 'picking_lists', 'users', ['completed_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_picking_lists_canceled_by_users'), 'picking_lists', 'users', ['canceled_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_picking_lists_started_by_users'), 'picking_lists', 'users', ['started_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_picking_lists_started_by_users'), 'picking_lists', type_='foreignkey')
    op.drop_constraint(op.f('fk_picking_lists_canceled_by_users'), 'picking_lists', type_='foreignkey')
    op.drop_constraint(op.f('fk_picking_lists_completed_by_users'), 'picking_lists', type_='foreignkey')
    op.drop_constraint(op.f('fk_picking_lists_assigned_to_users'), 'picking_lists', type_='foreignkey')
    op.drop_constraint(op.f('fk_picking_lists_printed_by_users'), 'picking_lists', type_='foreignkey')
    op.drop_index(op.f('ix_outbound_orders_reference_no'), table_name='outbound_orders')
    op.create_index(op.f('ix_outbound_orders_ob_type'), 'outbound_orders', ['ob_type'], unique=False)
    op.create_index(op.f('ix_outbound_orders_created_at'), 'outbound_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_reference'), 'inventory_transactions', ['reference_type', 'reference_id'], unique=False)
    op.create_unique_constraint(op.f('uq_inventory_lots_source_inbound_id'), 'inventory_lots', ['source_inbound_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_inventory_lots_lot_no'), 'inventory_lots', ['lot_no'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_fba_shipments_st_number'), table_name='fba_shipments')
    op.drop_index(op.f('ix_fba_shipments_shipment_id'), table_name='fba_shipments')
    op.drop_index(op.f('ix_fba_shipments_reference_no'), table_name='fba_shipments')
    op.create_unique_constraint(op.f('uq_fba_shipments_fba_no'), 'fba_shipments', ['fba_no'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_fba_shipments_created_at'), 'fba_shipments', ['created_at'], unique=False)
    op.drop_constraint(op.f('fk_bols_carrier_id_carriers'), 'bols', type_='foreignkey')
    op.drop_constraint(op.f('fk_bols_customer_id_customers'), 'bols', type_='foreignkey')
    op.drop_index(op.f('ix_bols_fba_shipment_id'), table_name='bols')
    op.add_column('bol_items', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
