export const COMPANY_ITEMS: Record<string, { title: string; group: string; note: string }> = {
  "user-management": { title: "User Management", group: "My Company", note: "Live." },
  "company-profile": { title: "Company Profile", group: "My Company", note: "Company name and warehouse identity." },
  "email-setting": { title: "Email Setting", group: "My Company", note: "Notification mail is not configured yet." },
  "access-control": { title: "Access Control", group: "My Company", note: "Page access follows signed-in role." },
  "trade-party": { title: "Trade Party", group: "My Company", note: "Maps to Yuki customers." },
  "area-group": { title: "Area Group", group: "My Company", note: "Regional warehouse grouping." },
  "warehouse-point-group": { title: "Warehouse Point Group", group: "My Company", note: "Related to West Coast 仓点 values." },
  zone: { title: "Zone", group: "My Company", note: "Warehouse zone / location grouping." },
  "service-setting": { title: "Service Setting", group: "My Company", note: "Inbound, FBA and outbound service types." },
  "commission-setting": { title: "Commission Setting", group: "My Company", note: "Not used by current operations." },
  "team-setting": { title: "Team Setting", group: "My Company", note: "Loading team roster." },
  "company-code": { title: "Company Code", group: "My Company", note: "Legal entity / bill-to codes." },
  "preference-setting": { title: "Preference Setting", group: "My Company", note: "Timezone America/Los_Angeles and default warehouse." },
  "ocean-carrier": { title: "Ocean Carrier", group: "Entities", note: "Maps to Yuki carrier master." },
  terminals: { title: "Terminals", group: "Entities", note: "Port / rail terminals." },
  "shipping-modes": { title: "Shipping Modes", group: "Entities", note: "Already represented on outbound types." },
  "force-majeure": { title: "Force Majeure Events", group: "Entities", note: "Can later feed Trouble Shoot." },
  "gl-codes": { title: "General Ledger Codes", group: "Controller Tools", note: "Accounting is out of current WMS scope." },
  "billing-codes": { title: "Billing Codes", group: "Controller Tools", note: "Not enabled." },
  "bank-account": { title: "Bank Account", group: "Controller Tools", note: "Not part of warehouse operations." },
  "account-block": { title: "Account Block", group: "Controller Tools", note: "Not part of warehouse operations." },
  "income-statement": { title: "Income Statement", group: "Controller Tools", note: "Not part of warehouse operations." },
  "balance-sheet": { title: "Balance Sheet", group: "Controller Tools", note: "Not part of warehouse operations." },
};
