
import { QuestionCircleOutlined, UploadOutlined } from '@ant-design/icons'
import { Alert, Button, DatePicker, Descriptions, Drawer, Empty, Input, Popover, Select, Space, Table, Tag, Typography, Upload, message } from 'antd'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useMemo, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { getContainerTracking, getContainerTrackings, importContainerTracking } from '../api/containerTracking'
import type { ColumnsType } from 'antd/es/table'
import type { ContainerTrackingRow } from '../api/containerTracking'
import { DispatchPriorityTag, DispatchReadinessTag, OutboundDateCell } from '../components/DispatchIndicators'

const colors:Record<string,string>={PLANNED:'default',IN_TRANSIT:'blue',DELIVERY_SCHEDULED:'cyan',DELIVERED:'orange',WAREHOUSE_RECEIVED:'purple',EMPTY:'gold',COMPLETED:'green'}
const dateText=(value?:string|null)=>{if(!value)return'--';const[y,m,d]=value.slice(0,10).split('-');return`${m}/${d}/${y}`}
const explanation=<Space direction="vertical" size={4} style={{maxWidth:360}}><Typography.Text strong>Dispatch intelligence</Typography.Text><Typography.Text>Earliest Outbound: earliest active scheduled outbound allocation.</Typography.Text><Typography.Text>Days Remaining: calendar days from the warehouse business date.</Typography.Text><Typography.Text>Priority: CRITICAL today/overdue; HIGH 1–2 days; MEDIUM 3–5; NORMAL later/unscheduled.</Typography.Text><Typography.Text>Readiness: inventory/allocation execution state; exceptions are BLOCKED.</Typography.Text></Space>
const CONTAINER_NUMBER_RE=/^[A-Z]{4}[0-9]{7}$/
const normalizeContainerNumber=(raw?:string|null)=>String(raw||'').replace(/[\s-]/g,'').toUpperCase()
const openContainerTrack=(raw?:string|null)=>{
  const container=normalizeContainerNumber(raw)
  if(!CONTAINER_NUMBER_RE.test(container)){
    message.warning('非法柜号，无法查柜')
    return
  }
  window.open(`https://www.track-trace.com/container?number=${container}`,'_blank','noopener')
}
const TrackButton=({containerNumber}:{containerNumber?:string|null})=>{
  if(!containerNumber)return null
  return <Button size="small" onClick={(e)=>{e.stopPropagation();openContainerTrack(containerNumber)}}>Track / 查柜</Button>
}

export function ContainerTrackingPage(){
 const[sp,setSp]=useSearchParams();const navigate=useNavigate();const qc=useQueryClient();const[id,setId]=useState(Number(sp.get('selected')||0))
 const params=useMemo(()=>({page:Number(sp.get('page')||1),per_page:20,q:sp.get('q')||undefined,status:sp.get('status')||undefined,outbound_window:sp.get('outbound_window')||undefined,outbound_from:sp.get('outbound_from')||undefined,outbound_to:sp.get('outbound_to')||undefined,dispatch_priority:sp.get('priority')||undefined,sort_by:sp.get('sort_by')||'pod_eta',sort_order:sp.get('sort_order')||'desc'}),[sp])
 const patch=(values:Record<string,unknown>)=>{const q=new URLSearchParams(sp);Object.entries(values).forEach(([k,v])=>v==null||v===''?q.delete(k):q.set(k,String(v)));setSp(q,{replace:true})}
 const list=useQuery({queryKey:['container-tracking',params],queryFn:()=>getContainerTrackings(params)});const detail=useQuery({queryKey:['container-tracking-detail',id],queryFn:()=>getContainerTracking(id),enabled:!!id})
 const cols:ColumnsType<ContainerTrackingRow>=[{title:'Container',dataIndex:'container_number',fixed:'left',render:(v,r)=><Button type="link" onClick={()=>{setId(r.id);patch({selected:r.id})}}>{v}</Button>},{title:'Track / 查柜',key:'container_track',width:110,render:(_,r)=><TrackButton containerNumber={r.container_number}/>},{title:'Status',dataIndex:'tracking_status',render:v=><Tag color={colors[v]}>{v}</Tag>},{title:'最早出库时间',dataIndex:'earliest_outbound_date',sorter:true,render:(v,r)=><OutboundDateCell value={v} days={r.outbound_days_remaining}/>},{title:'Days Left',dataIndex:'outbound_days_remaining',sorter:true,render:v=>v==null?'--':v},{title:'Dispatch',dataIndex:'dispatch_priority',sorter:true,render:v=><DispatchPriorityTag value={v}/>},{title:'Inbound',dataIndex:'inbound_date',render:dateText},{title:'Warehouse Days',dataIndex:'warehouse_days',sorter:true,render:v=>v??'--'},{title:'MBL',dataIndex:'mbl_number'},{title:'HBL',dataIndex:'hbl_number'},{title:'POD ETA',dataIndex:'pod_eta'},{title:'Warehouse',dataIndex:'delivery_warehouse_raw'},{title:'WA Received',dataIndex:'wa_received_at'}]
 const basic=detail.data?.basic
 return <div className="page-container"><div className="page-header"><div><h2>Container Tracking / 柜况追踪</h2><Popover content={explanation} title="How dispatch fields work"><Button type="text" size="small" icon={<QuestionCircleOutlined/>}>Dispatch rules</Button></Popover></div><Upload accept=".csv" showUploadList={false} beforeUpload={async file=>{try{const result=await importContainerTracking(file);message.success(`Imported ${result.created} created, ${result.updated} updated`);qc.invalidateQueries({queryKey:['container-tracking']})}catch(error){message.error('Import failed. Check file format and your permission.')}return false}}><Button icon={<UploadOutlined/>}>Import shipmentexport.csv</Button></Upload></div>
 <div className="toolbar"><Space wrap><Input.Search allowClear placeholder="Search Container / MBL / HBL / Warehouse" value={sp.get('q')||''} onChange={e=>patch({q:e.target.value,page:1})}/><Select allowClear placeholder="Outbound Date" value={params.outbound_window} onChange={v=>patch({outbound_window:v,outbound_from:undefined,outbound_to:undefined,page:1})} options={[['overdue','Overdue'],['today','Today'],['tomorrow','Tomorrow'],['next_3','Next 3 Days'],['next_7','Next 7 Days'],['none','No Scheduled Outbound']].map(([value,label])=>({value,label}))}/><DatePicker.RangePicker aria-label="Custom outbound date range" onChange={(_,values)=>patch({outbound_from:values[0],outbound_to:values[1],outbound_window:undefined,page:1})}/><Select allowClear placeholder="Dispatch Priority" value={params.dispatch_priority} onChange={v=>patch({priority:v,page:1})} options={['CRITICAL','HIGH','MEDIUM','NORMAL'].map(value=>({value,label:value}))}/><Button onClick={()=>setSp(new URLSearchParams())}>Reset</Button></Space></div>
 {list.isError&&<Alert type="error" showIcon message="Unable to load container dispatch data" description="Refresh the page or verify that your account can view warehouse data."/>}<Table size="small" rowKey="id" scroll={{x:1500}} loading={list.isLoading} dataSource={list.data?.data||[]} columns={cols} locale={{emptyText:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="No containers match the current dispatch filters"/>}} pagination={{current:params.page,total:list.data?.meta?.total,pageSize:20,onChange:p=>patch({page:p})}} onChange={(_,__,sorter)=>{const current=Array.isArray(sorter)?sorter[0]:sorter;if(current?.field)patch({sort_by:current.field,sort_order:current.order==='ascend'?'asc':'desc'})}}/>
 <Drawer width={760} title="Container Tracking Detail" open={!!id} onClose={()=>{setId(0);patch({selected:undefined})}}>{detail.isError?<Alert type="error" showIcon message="Unable to load dispatch detail" description="The container may no longer exist or access may have changed."/>:basic?<><Space align="center"><h3 style={{margin:0}}>{basic.container_number}</h3><TrackButton containerNumber={basic.container_number}/></Space><h4>Dispatch Overview</h4><Descriptions size="small" bordered column={2} items={[{key:'date',label:'Earliest Outbound',children:<OutboundDateCell value={basic.earliest_outbound_date} days={basic.outbound_days_remaining}/>},{key:'days',label:'Days Remaining',children:basic.outbound_days_remaining??'--'},{key:'priority',label:'Priority',children:<DispatchPriorityTag value={basic.dispatch_priority}/>},{key:'ready',label:'Readiness',children:<DispatchReadinessTag value={basic.dispatch_readiness}/>},{key:'inbound',label:'Inbound',children:dateText(basic.inbound_date)},{key:'aging',label:'Warehouse Days',children:basic.warehouse_days??'--'}]}/>{basic.dispatch_readiness==='NOT_READY'&&<Alert style={{marginTop:12}} type="warning" showIcon message="Not ready for dispatch" description="Inventory is unavailable or no valid remaining allocation exists."/>}<h4>Related FBA / Outbound Tasks</h4><Table size="small" pagination={false} rowKey={r=>`${r.outbound_id}-${r.fc_code||''}`} dataSource={detail.data?.related_outbound_tasks??[]} locale={{emptyText:'No active or completed outbound tasks'}} columns={[{title:'OB Number',dataIndex:'ob_no',render:(v,r)=><Button type="link" onClick={()=>navigate(`/outbound/dispatch?selected_ob=${r.outbound_id}`)}>{v}</Button>},{title:'FC',dataIndex:'fc_code'},{title:'Outbound Date',dataIndex:'outbound_date',render:dateText},{title:'Pallet',dataIndex:'pallet_qty'},{title:'Completed',dataIndex:'completed_pallet_qty'},{title:'Status',dataIndex:'status_name'},{title:'Picking',dataIndex:'picking_status',render:v=>v??'--'},{title:'BOL',dataIndex:'bol_no',render:v=>v||'--'}]}/></>:<Empty description="Select a container to view dispatch details"/>}</Drawer></div>
}
