import { Alert, Button, Card, Col, DatePicker, Empty, List, Progress, Row, Select, Space, Statistic, Table, Tag, Typography } from 'antd'
import { useQuery } from '@tanstack/react-query'
import dayjs, { Dayjs } from 'dayjs'
import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { getWarehouses } from '../api/masterData'
import { DashboardItem, getOperationsDashboard } from '../api/operationsDashboard'
const {RangePicker}=DatePicker,iso=(d:Dayjs)=>d.format('YYYY-MM-DD')
const ranges=(key:string):[Dayjs,Dayjs]=>{const t=dayjs();if(key==='yesterday')return[t.subtract(1,'day'),t.subtract(1,'day')];if(key==='7d')return[t.subtract(6,'day'),t];if(key==='month')return[t.startOf('month'),t];return[t,t]}
const pairs=(v:Record<string,number>)=>Object.entries(v).map(([key,count])=>({key,count}))
export function OperationsDashboardPage(){
 const nav=useNavigate(),[warehouse,setWarehouse]=useState<number>(),[range,setRange]=useState<[Dayjs,Dayjs]>(ranges('today'))
 const wh=useQuery({queryKey:['warehouses'],queryFn:getWarehouses}),params=useMemo(()=>({date_from:iso(range[0]),date_to:iso(range[1]),warehouse_id:warehouse}),[range,warehouse]),query=useQuery({queryKey:['operations-dashboard',params],queryFn:()=>getOperationsDashboard(params)}),data=query.data
 const open=(item:DashboardItem)=>nav(item.kind==='EXCEPTION'?`/trouble-shoot?selected=${item.entity_id}`:`/work-orders?selected=${item.entity_id}`),go=(path:string,filter:Record<string,string|number|undefined>)=>nav(`${path}?${new URLSearchParams(Object.entries(filter).filter(([,v])=>v!==undefined).map(([k,v])=>[k,String(v)])).toString()}`)
 const cards=data?[['Active Loads',data.summary.active_loads,'Snapshot',()=>go('/loads',{warehouse_id:warehouse})],['Outbound Ready / Active',`${data.summary.outbound_ready} / ${data.summary.outbound_active}`,'Snapshot',()=>go('/outbound/dispatch',{warehouse_id:warehouse})],['Open Work Orders',data.summary.open_work_orders,'Snapshot',()=>go('/work-orders',{status:'OPEN',warehouse_id:warehouse})],['Open Exceptions',data.summary.open_exceptions,'Snapshot',()=>go('/trouble-shoot',{status:'OPEN',warehouse_id:warehouse})],['Critical',data.summary.critical_open_exceptions,'Snapshot',()=>go('/trouble-shoot',{status:'OPEN',severity:'CRITICAL',warehouse_id:warehouse})],['Completed Work Orders',data.summary.completed_work_orders_period,'Selected period',()=>go('/work-orders',{status:'COMPLETED',warehouse_id:warehouse})]] as const:[]
 return <div className="page operations-dashboard"><div className="page-heading"><div><Typography.Title level={4}>Operations Command Dashboard</Typography.Title><Typography.Text type="secondary">Live execution, exceptions and warehouse workload</Typography.Text></div><Button onClick={()=>query.refetch()}>Refresh</Button></div><div className="dashboard-filters"><Select allowClear value={warehouse} placeholder="All accessible warehouses" style={{minWidth:240}} options={(wh.data??[]).map(w=>({value:w.id,label:`${w.warehouse_code} — ${w.warehouse_name}`}))} onChange={setWarehouse}/><Space.Compact><Button onClick={()=>setRange(ranges('today'))}>Today</Button><Button onClick={()=>setRange(ranges('yesterday'))}>Yesterday</Button><Button onClick={()=>setRange(ranges('7d'))}>7 days</Button><Button onClick={()=>setRange(ranges('month'))}>This month</Button></Space.Compact><RangePicker value={range} allowClear={false} onChange={v=>v&&setRange([v[0]!,v[1]!])}/></div>
 {query.isError?<Alert type="error" showIcon message="Unable to load operations dashboard" action={<Button onClick={()=>query.refetch()}>Retry</Button>}/>:query.isLoading?<Row gutter={[12,12]}>{Array.from({length:6},(_,i)=><Col span={4} key={i}><Card loading/></Col>)}</Row>:!data?<Empty/>:<><Row gutter={[12,12]}>{cards.map(([title,value,note,click])=><Col xs={24} sm={12} xl={4} key={title}><Card hoverable onClick={click}><Statistic title={title} value={value}/><Typography.Text type="secondary">{note}</Typography.Text></Card></Col>)}</Row>
 <Row gutter={[12,12]} className="dashboard-row"><Col xs={24} xl={8}><Card title="Load flow · selected period"><Statistic title="Loads created" value={data.loads.created_period}/><div className="tag-cloud">{pairs(data.loads.created_period_by_current_status).map(x=><Tag key={x.key}>{x.key} {x.count}</Tag>)}</div><Typography.Text type="secondary">Average outbounds / created load: {data.loads.average_outbounds_per_period_load??'—'}</Typography.Text></Card></Col><Col xs={24} xl={8}><Card title="Work order execution · snapshot">{data.execution_funnel.map(x=><div className="metric-line" key={x.stage}><span>{x.stage}</span><b>{x.count}</b></div>)}<div className="metric-line"><span>Overdue (scheduled only)</span><b>{data.work_orders.overdue_snapshot}</b></div></Card></Col><Col xs={24} xl={8}><Card title="Exception control"><div className="metric-line"><span>Resolved · selected period</span><b>{data.exceptions.resolved_period}</b></div><div className="metric-line"><span>Average resolution</span><b>{data.exceptions.average_resolution_hours_period==null?'—':`${data.exceptions.average_resolution_hours_period}h`}</b></div><div className="tag-cloud">{pairs(data.exceptions.open_severity_snapshot).map(x=><Tag color={x.key==='CRITICAL'?'red':x.key==='HIGH'?'orange':'default'} key={x.key}>{x.key} {x.count}</Tag>)}</div></Card></Col></Row>
 <Row gutter={[12,12]} className="dashboard-row"><Col xs={24} xl={8}><Card title="Aging · open snapshot"><Typography.Text strong>Work orders (created at)</Typography.Text>{pairs(data.work_orders.aging_snapshot).map(x=><div className="metric-line" key={x.key}><span>{x.key.replaceAll('_','–')}</span><b>{x.count}</b></div>)}<Typography.Text strong>Exceptions (reported at)</Typography.Text>{pairs(data.exceptions.aging_snapshot).map(x=><div className="metric-line" key={x.key}><span>{x.key.replaceAll('_','–')}</span><b>{x.count}</b></div>)}</Card></Col><Col xs={24} xl={8}><Card title="Exception types · open snapshot">{pairs(data.exceptions.open_type_snapshot).length?pairs(data.exceptions.open_type_snapshot).map(x=><div key={x.key}><div className="metric-line"><span>{x.key}</span><b>{x.count}</b></div><Progress percent={data.summary.open_exceptions?Math.round(x.count/data.summary.open_exceptions*100):0} showInfo={false} size="small"/></div>):<Empty image={Empty.PRESENTED_IMAGE_SIMPLE}/>}</Card></Col><Col xs={24} xl={8}><Card title="Attention queue"><List locale={{emptyText:'Nothing needs immediate attention'}} dataSource={data.attention} renderItem={item=><List.Item className="dashboard-link" onClick={()=>open(item)}><List.Item.Meta title={<>{item.reference} <Tag color="red">{item.reason}</Tag></>} description={item.label}/></List.Item>}/></Card></Col></Row>
 {data.warehouses.length>1&&<Card title="Warehouse breakdown" className="dashboard-row"><Table size="small" pagination={false} rowKey="warehouse_id" dataSource={data.warehouses} columns={[{title:'Warehouse',render:(_,r)=>`${r.warehouse_code} — ${r.warehouse_name}`},{title:'Open work orders',dataIndex:'open_work_orders'},{title:'Open exceptions',dataIndex:'open_exceptions'}]}/></Card>}<Card title="Recent operational activity" className="dashboard-row"><List locale={{emptyText:'No recent activity'}} dataSource={data.recent_activity} renderItem={item=><List.Item className="dashboard-link" onClick={()=>open(item)}><List.Item.Meta title={`${item.reference} · ${item.event_type}`} description={item.message||item.created_at}/><Tag>{item.kind.replace('_',' ')}</Tag></List.Item>}/></Card></>}</div>
}
