package com.dlxyuki.wms.pickingbol;
import com.dlxyuki.wms.config.ApiException;import com.dlxyuki.wms.user.UserAccount;import java.io.ByteArrayOutputStream;import java.util.*;import org.apache.poi.xssf.usermodel.XSSFWorkbook;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;
@Service public class PickingBolService{
 static final List<String> HEADERS=List.of("Picking No","OB ID","Sequence","Location","Container","FC","Marking","Pallet","Carton","Weight LBS","CBM");private final PickingBolRepository repository;PickingBolService(PickingBolRepository r){repository=r;}List<Map<String,Object>> list(UserAccount u){return repository.listPicking(u);}Map<String,Object> get(long id,UserAccount u){return repository.findPicking(id,u).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Picking list not found"));}byte[] export(long id,UserAccount u){var p=get(id,u);return workbook(p,repository.pickingItems(id));}
 static final List<String> BOL_HEADERS=List.of("BOL No","Outbound No","Ship From","Ship To","FC","Container","Pallet","Carton","Weight LBS","CBM");List<Map<String,Object>> listBols(UserAccount u){return repository.listBols(u);}Map<String,Object> getBol(long id,UserAccount u){return repository.findBol(id,u).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"BOL not found"));}byte[] exportBol(long id,UserAccount u){var b=getBol(id,u);return bolWorkbook(b,repository.bolItems(id));}
 public byte[] exportBolPdf(long id,UserAccount u){var b=getBol(id,u);return bolPdf(b,repository.bolItems(id));}
 static byte[] workbook(Map<String,Object> p,List<Map<String,Object>> items){try(var b=new XSSFWorkbook();var out=new ByteArrayOutputStream()){var s=b.createSheet("Picking List");var h=s.createRow(0);for(int i=0;i<HEADERS.size();i++)h.createCell(i).setCellValue(HEADERS.get(i));int n=1;for(var item:items){var r=s.createRow(n++);int c=0;r.createCell(c++).setCellValue(String.valueOf(p.get("picking_no")));r.createCell(c++).setCellValue(String.valueOf(p.get("outbound_order_id")));for(String k:List.of("sequence_no","location_code","container_number","fc_code","marking","planned_pallet_qty","planned_carton_qty","planned_weight_lbs","planned_cbm")){Object v=item.get(k);r.createCell(c++).setCellValue(v==null?"":v.toString());}}b.write(out);return out.toByteArray();}catch(Exception e){throw new IllegalStateException("Unable to create picking list workbook",e);}}
 static byte[] bolWorkbook(Map<String,Object> bol,List<Map<String,Object>> items){try(var b=new XSSFWorkbook();var out=new ByteArrayOutputStream()){var s=b.createSheet("BOL");var h=s.createRow(0);for(int i=0;i<BOL_HEADERS.size();i++)h.createCell(i).setCellValue(BOL_HEADERS.get(i));int n=1;for(var item:items){var r=s.createRow(n++);int c=0;r.createCell(c++).setCellValue(String.valueOf(bol.get("bol_no")));for(String k:List.of("ob_no","ship_from_address","ship_to_address","amazon_fc_code","container_number","pallet_qty","carton_qty","weight_lbs","cbm")){Object v=item.get(k);r.createCell(c++).setCellValue(v==null?"":v.toString());}}b.write(out);return out.toByteArray();}catch(Exception e){throw new IllegalStateException("Unable to create BOL workbook",e);}}
 static byte[] bolPdf(Map<String,Object> bol,List<Map<String,Object>> items){
  String outbound=items.isEmpty()?"":value(items.getFirst().get("ob_no"));
  List<String> lines=new ArrayList<>(List.of("DLX Yuki WMS - BILL OF LADING","BOL No: "+value(bol.get("bol_no")),"Outbound: "+outbound,"Ship From: "+value(bol.get("ship_from_name"))+", "+value(bol.get("ship_from_address")),"Ship To: "+value(bol.get("ship_to_name"))+", "+value(bol.get("ship_to_address")),"Items:"));
  for(var i:items)lines.add(value(i.get("container_number"))+" | "+value(i.get("pallet_qty"))+" PLT | "+value(i.get("carton_qty"))+" CTN | "+value(i.get("weight_lbs"))+" LBS | "+value(i.get("cbm"))+" CBM");
  StringBuilder commands=new StringBuilder("BT /F1 10 Tf 40 760 Td ");for(int n=0;n<lines.size();n++){if(n>0)commands.append(" 0 -16 Td ");commands.append('(').append(pdfEscape(lines.get(n))).append(") Tj");}commands.append(" ET");byte[] stream=commands.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8);
  var out=new ByteArrayOutputStream();try{out.write("%PDF-1.4\n1 0 obj<< /Type /Catalog /Pages 2 0 R>>endobj\n2 0 obj<< /Type /Pages /Kids [3 0 R] /Count 1>>endobj\n3 0 obj<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources<< /Font<< /F1 5 0 R>>>>>>endobj\n4 0 obj<< /Length ".getBytes(java.nio.charset.StandardCharsets.US_ASCII));out.write(Integer.toString(stream.length).getBytes(java.nio.charset.StandardCharsets.US_ASCII));out.write(">>stream\n".getBytes(java.nio.charset.StandardCharsets.US_ASCII));out.write(stream);out.write("\nendstream endobj\n5 0 obj<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica>>endobj\ntrailer<< /Root 1 0 R>>\n%%EOF".getBytes(java.nio.charset.StandardCharsets.US_ASCII));return out.toByteArray();}catch(java.io.IOException e){throw new IllegalStateException("Unable to create BOL PDF",e);}
 }
 private static String value(Object v){return v==null?"":v.toString();}private static String pdfEscape(String s){return s.replace("\\","\\\\").replace("(","\\(").replace(")","\\)");}
}
