package com.dlxyuki.wms.fba;

import com.dlxyuki.wms.user.UserAccount;
import java.math.*;
import java.sql.*;
import java.time.*;
import java.time.temporal.ChronoUnit;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.*;
import org.springframework.stereotype.Repository;

@Repository
public class FbaRepository {
    private static final ZoneId BUSINESS_ZONE=ZoneId.of("America/Los_Angeles");
    private static final String BASE="""
      with ag as (
        select a.fba_shipment_id,count(distinct a.inventory_lot_id) lot_count,
          coalesce(sum(a.allocated_pallet_qty),0) pallets,coalesce(sum(a.allocated_carton_qty),0) cartons,
          coalesce(sum(a.allocated_weight_lbs),0) weight,coalesce(sum(a.allocated_cbm),0) cbm,
          min(i.inbound_date) oldest,max(i.inbound_date) newest,
          avg(greatest(0,(current_timestamp at time zone 'America/Los_Angeles')::date-i.inbound_date)) average_aging,
          array_remove(array_agg(distinct i.container_number),null) containers,
          array_remove(array_agg(distinct coalesce(l.location_code,i.raw_location_text)),null) locations
        from fba_inventory_allocations a join inventory_lots i on i.id=a.inventory_lot_id
        left join warehouse_locations l on l.id=i.location_id group by a.fba_shipment_id),
      latest_ob as (select distinct on (fba_shipment_id) * from outbound_orders where fba_shipment_id is not null order by fba_shipment_id,id desc),
      ob_early as (select fba_shipment_id,min(schedule_pickup_at) earliest from outbound_orders where status in (0,1,2,3,4,7) and schedule_pickup_at is not null group by fba_shipment_id),
      latest_pick as (select distinct on (o.fba_shipment_id) p.*,o.fba_shipment_id from picking_lists p join outbound_orders o on o.id=p.outbound_order_id order by o.fba_shipment_id,p.id desc),
      pick_count as (select o.fba_shipment_id,count(*) count from picking_lists p join outbound_orders o on o.id=p.outbound_order_id group by o.fba_shipment_id),
      latest_bol as (select distinct on (fba_shipment_id) * from bols where fba_shipment_id is not null order by fba_shipment_id,id desc)
      select s.*,c.customer_code,c.customer_name,w.warehouse_code,w.warehouse_name,
        cr.carrier_code,cr.carrier_name,fc.fc_name,fc.address_line1,fc.address_line2,fc.city fc_city,fc.state fc_state,fc.zip_code fc_zip,fc.country fc_country,
        u.username creator_username,u.display_name creator_name,
        coalesce(ag.lot_count,0) lot_count,coalesce(ag.pallets,0) pallets,coalesce(ag.cartons,0) cartons,
        coalesce(ag.weight,0) weight,coalesce(ag.cbm,0) cbm,ag.oldest,ag.newest,ag.average_aging,coalesce(ag.containers,array[]::varchar[]) containers,coalesce(ag.locations,array[]::varchar[]) locations,
        ob.id ob_id,ob.ob_no,ob.status ob_status,ob.schedule_pickup_at ob_scheduled,ob.delivery_appointment_time ob_appointment,
        oe.earliest,coalesce(pc.count,0) picking_count,lp.id picking_id,lp.picking_no,lp.status picking_status,
        lb.id bol_id,lb.bol_no,lb.status bol_status
      from fba_shipments s left join customers c on c.id=s.customer_id join warehouses w on w.id=s.warehouse_id
      left join carriers cr on cr.id=s.carrier_id left join amazon_fc_addresses fc on fc.id=s.amazon_fc_address_id
      join users u on u.id=s.created_by left join ag on ag.fba_shipment_id=s.id left join latest_ob ob on ob.fba_shipment_id=s.id
      left join ob_early oe on oe.fba_shipment_id=s.id left join latest_pick lp on lp.fba_shipment_id=s.id
      left join pick_count pc on pc.fba_shipment_id=s.id left join latest_bol lb on lb.fba_shipment_id=s.id
      """;
    private static final String BASE_ACTIVE=BASE.replace(
      "left join warehouse_locations l on l.id=i.location_id group by a.fba_shipment_id",
      "left join warehouse_locations l on l.id=i.location_id where (a.allocated_pallet_qty<>0 or a.allocated_carton_qty<>0 or a.allocated_weight_lbs<>0 or a.allocated_cbm<>0) group by a.fba_shipment_id");
    private final NamedParameterJdbcTemplate jdbc;
    public FbaRepository(JdbcTemplate jdbc) { this.jdbc=new NamedParameterJdbcTemplate(jdbc); }

    Map<String,Object> list(FbaQuery q,UserAccount u) {
        MapSqlParameterSource p=new MapSqlParameterSource(); List<String> c=new ArrayList<>(); scope(u,p,c);
        like(c,p,"fba_no",q.fbaNo(),"s.fba_no"); like(c,p,"amazon_fc",q.amazonFcCode(),"s.amazon_fc_code");
        exact(c,p,"customer_id",q.customerId(),"s.customer_id"); exact(c,p,"warehouse_id",q.warehouseId(),"s.warehouse_id"); exact(c,p,"carrier_id",q.carrierId(),"s.carrier_id"); exact(c,p,"status",q.status(),"s.status");
        if(q.containerNumber()!=null){p.addValue("container","%"+q.containerNumber()+"%");c.add("exists(select 1 from fba_inventory_allocations ax join inventory_lots ix on ix.id=ax.inventory_lot_id where ax.fba_shipment_id=s.id and ix.container_number ilike :container)");}
        if(q.locationId()!=null){p.addValue("location_id",q.locationId());c.add("exists(select 1 from fba_inventory_allocations ax join inventory_lots ix on ix.id=ax.inventory_lot_id where ax.fba_shipment_id=s.id and ix.location_id=:location_id)");}
        if(q.appointmentFrom()!=null){p.addValue("apt_from",q.appointmentFrom());c.add("s.appointment_time>=cast(:apt_from as timestamptz)");} if(q.appointmentTo()!=null){p.addValue("apt_to",q.appointmentTo());c.add("s.appointment_time<=cast(:apt_to as timestamptz)");}
        if(q.q()!=null){p.addValue("q","%"+q.q()+"%");c.add("(s.fba_no ilike :q or s.amazon_fc_code ilike :q or s.reference_no ilike :q or s.shipment_id ilike :q or s.st_number ilike :q or s.remark ilike :q or exists(select 1 from fba_inventory_allocations ax join inventory_lots ix on ix.id=ax.inventory_lot_id where ax.fba_shipment_id=s.id and (ix.container_number ilike :q or ix.lot_no ilike :q)))");}
        List<Map<String,Object>> rows=jdbc.query(BASE_ACTIVE+where(c),p,(r,n)->fba(r));
        post(rows,q.priorityLevel(),q.agingMin(),q.agingMax(),false); sort(rows,q.sortBy(),q.sortOrder());
        return page(rows,q.page(),q.perPage());
    }

    Optional<Map<String,Object>> find(long id,UserAccount u){MapSqlParameterSource p=new MapSqlParameterSource("id",id);List<String> c=new ArrayList<>(List.of("s.id=:id"));scope(u,p,c);return jdbc.query(BASE_ACTIVE+where(c),p,(r,n)->fba(r)).stream().findFirst();}

    Map<String,Object> workbench(WorkbenchQuery q,UserAccount u){return workbench(q,u,null);}

    Map<String,Object> workbench(WorkbenchQuery q,UserAccount u,Collection<Long> fbaIds){
        MapSqlParameterSource p=new MapSqlParameterSource();List<String> c=new ArrayList<>();scope(u,p,c);
        if(fbaIds!=null){if(fbaIds.isEmpty())c.add("false");else{p.addValue("fba_ids",fbaIds);c.add("s.id in (:fba_ids)");}}
        exact(c,p,"warehouse_id",q.warehouseId(),"s.warehouse_id");exact(c,p,"customer_id",q.customerId(),"s.customer_id");exact(c,p,"carrier_id",q.carrierId(),"s.carrier_id");exact(c,p,"fba_status",q.fbaStatus(),"s.status");
        exact(c,p,"ob_status",q.outboundStatus(),"ob.status");exact(c,p,"pick_status",q.pickingStatus(),"lp.status");exact(c,p,"bol_status",q.bolStatus(),"lb.status");
        like(c,p,"amazon_fc",q.amazonFcCode(),"s.amazon_fc_code");like(c,p,"st_number",q.stNumber(),"s.st_number");like(c,p,"po_number",q.poNumber(),"s.po_number");
        if(q.containerNumber()!=null){p.addValue("container","%"+q.containerNumber()+"%");c.add("exists(select 1 from fba_inventory_allocations ax join inventory_lots ix on ix.id=ax.inventory_lot_id where ax.fba_shipment_id=s.id and ix.container_number ilike :container)");}
        if(q.locationId()!=null){p.addValue("location_id",q.locationId());c.add("exists(select 1 from fba_inventory_allocations ax join inventory_lots ix on ix.id=ax.inventory_lot_id where ax.fba_shipment_id=s.id and ix.location_id=:location_id)");}
        range(c,p,"unload_from",q.unloadFrom(),"ag.oldest", "date",true);range(c,p,"unload_to",q.unloadTo(),"ag.oldest","date",false);
        range(c,p,"scheduled_from",q.scheduledFrom(),"ob.schedule_pickup_at","timestamptz",true);range(c,p,"scheduled_to",q.scheduledTo(),"ob.schedule_pickup_at","timestamptz",false);
        range(c,p,"appointment_from",q.appointmentFrom(),"ob.delivery_appointment_time","timestamptz",true);range(c,p,"appointment_to",q.appointmentTo(),"ob.delivery_appointment_time","timestamptz",false);
        if(q.q()!=null){p.addValue("q","%"+q.q()+"%");c.add("(s.fba_no ilike :q or s.shipment_id ilike :q or s.st_number ilike :q or s.po_number ilike :q or s.reference_no ilike :q or ob.ob_no ilike :q or lp.picking_no ilike :q or lb.bol_no ilike :q or exists(select 1 from fba_inventory_allocations ax join inventory_lots ix on ix.id=ax.inventory_lot_id where ax.fba_shipment_id=s.id and (ix.container_number ilike :q or ix.fc_code ilike :q or ix.lot_no ilike :q)))");}
        List<Map<String,Object>> rows=jdbc.query(BASE+where(c),p,(r,n)->{Map<String,Object>x=workbenchRow(r);if(fbaIds!=null)x.put("carrier",r.getString("carrier_name"));return x;});
        post(rows,q.priority(),q.agingMin(),q.agingMax(),q.onlyOld());
        Map<String,Integer> counts=new LinkedHashMap<>();for(String s:List.of("all","waiting_picking","waiting_appointment","waiting_outbound","completed","exception"))counts.put(s,0);
        counts.put("all",rows.size());for(Map<String,Object> x:rows){String s=(String)x.get("workbench_stage");counts.put(s,counts.get(s)+1);}
        if(!"all".equals(q.stage()))rows.removeIf(x->!q.stage().equals(x.get("workbench_stage")));
        Map<String,Object> summary=summary(rows);sort(rows,q.sortBy(),q.sortOrder());long total=rows.size();Map<String,Object> result=page(rows,q.page(),q.perPage());
        @SuppressWarnings("unchecked") Map<String,Object> meta=(Map<String,Object>)result.get("meta");meta.put("attention_threshold_days",attentionDays());meta.put("trailer_default_pallet_capacity",26);
        result.put("summary",summary);result.put("stage_counts",counts);result.put("permissions",permissions(u));return result;
    }

    Optional<Map<String,Object>> workbenchDetail(long id,UserAccount u){
        MapSqlParameterSource p=new MapSqlParameterSource("id",id);List<String> c=new ArrayList<>(List.of("s.id=:id"));scope(u,p,c);
        List<Map<String,Object>> found=jdbc.query(BASE+where(c),p,(r,n)->workbenchRow(r));if(found.isEmpty())return Optional.empty();Map<String,Object> row=found.get(0);
        Map<String,Object> basic=new LinkedHashMap<>();for(String k:List.of("id","fba_no","customer","warehouse","amazon_fc_code","amazon_fc_name","fc_address_missing","shipment_id","st_number","po_number","reference_no","scheduled_pickup_at","appointment_time","carrier","status","workbench_stage","workbench_stage_name","created_at"))basic.put(k,row.get(k));basic.put("internal_fba_no",row.get("fba_no"));basic.put("status_name",statusName((int)row.get("status")));
        Map<String,Object> fbaMeta=jdbc.query("select concat_ws(', ',fc.address_line1,fc.city,fc.state,fc.zip_code) amazon_fc_address,u.display_name created_by,s.remark from fba_shipments s left join amazon_fc_addresses fc on fc.id=s.amazon_fc_address_id join users u on u.id=s.created_by where s.id=:id",Map.of("id",id),(r,n)->Map.<String,Object>of("amazon_fc_address",Objects.toString(r.getString(1),""),"created_by",Objects.toString(r.getString(2),""),"remark",Objects.toString(r.getString(3),""))).get(0);basic.putAll(fbaMeta);
        List<Map<String,Object>> sources=allocationRows(id,(String)row.get("amazon_fc_code"));Long obId=(Long)row.get("outbound_id");
        List<Map<String,Object>> picking=obId==null?List.of():jdbc.query("select * from picking_lists where outbound_order_id=:id order by id desc",Map.of("id",obId),(r,n)->rowMap(r));
        Map<String,Object> outbound=obId==null?null:jdbc.query("select * from outbound_orders where id=:id",Map.of("id",obId),(r,n)->rowMap(r)).stream().findFirst().orElse(null);
        Long bolId=(Long)row.get("bol_id");Map<String,Object> bol=bolId==null?null:jdbc.query("select * from bols where id=:id",Map.of("id",bolId),(r,n)->rowMap(r)).stream().findFirst().orElse(null);
        String stage=(String)row.get("workbench_stage");List<Map<String,Object>> workflow=workflow(stage,!picking.isEmpty(),bol!=null,outbound);
        List<Long> auditIds=new ArrayList<>(List.of(id));if(obId!=null)auditIds.add(obId);for(Map<String,Object>x:picking)auditIds.add(((Number)x.get("id")).longValue());if(bolId!=null)auditIds.add(bolId);
        List<Map<String,Object>> audit=jdbc.query("select a.created_at,u.display_name,a.action,a.entity_type,a.after_data,a.before_data from audit_logs a left join users u on u.id=a.user_id where a.entity_id in (:ids) order by a.created_at desc limit 100",Map.of("ids",auditIds),(r,n)->{Map<String,Object>x=new LinkedHashMap<>();x.put("time",time(r,"created_at"));x.put("user",Optional.ofNullable(r.getString("display_name")).orElse("绯荤粺"));x.put("action",r.getString("action"));x.put("entity",r.getString("entity_type"));Object detail=r.getObject("after_data");x.put("detail",detail!=null?detail:r.getObject("before_data"));return x;});
        Map<String,Object> perms=new LinkedHashMap<>(permissions(u));if("completed".equals(stage))perms.put("can_operate",false);Map<String,Object> out=new LinkedHashMap<>();out.put("basic",basic);out.put("inventory_sources",sources);out.put("picking",picking);out.put("bol",bol);out.put("outbound",outbound);out.put("audit",audit);out.put("workflow",workflow);out.put("permissions",perms);return Optional.of(out);
    }

    private Map<String,Object> fba(ResultSet r)throws SQLException{
        Map<String,Object> x=new LinkedHashMap<>();x.put("id",r.getLong("id"));x.put("fba_no",r.getString("fba_no"));Long cid=nlong(r,"customer_id");x.put("customer",cid==null?null:ref(cid,r.getString("customer_code"),r.getString("customer_name")));x.put("warehouse",ref(r.getLong("warehouse_id"),r.getString("warehouse_code"),r.getString("warehouse_name")));
        x.put("amazon_fc_code",r.getString("amazon_fc_code"));x.put("amazon_fc_name",r.getString("fc_name"));x.put("amazon_fc_address",address(r));x.put("fc_address_missing",r.getObject("amazon_fc_address_id")==null);int status=r.getInt("status");x.put("status",status);x.put("status_name",statusName(status));Long carrier=nlong(r,"carrier_id");x.put("carrier",carrier==null?null:ref(carrier,r.getString("carrier_code"),r.getString("carrier_name")));
        x.put("scheduled_pickup_at",time(r,"scheduled_pickup_at"));x.put("appointment_time",time(r,"appointment_time"));for(String k:List.of("reference_no","shipment_id","st_number","remark"))x.put(k,r.getString(k));quantities(x,r);aging(x,r);x.put("created_by",userRef(r.getLong("created_by"),r.getString("creator_name")));x.put("created_at",time(r,"created_at"));x.put("updated_at",time(r,"updated_at"));return x;
    }
    private Map<String,Object> workbenchRow(ResultSet r)throws SQLException{
        Map<String,Object>x=new LinkedHashMap<>();x.put("id",r.getLong("id"));for(String k:List.of("fba_no","shipment_id","st_number","po_number","reference_no"))x.put(k,r.getString(k));x.put("customer_id",nlong(r,"customer_id"));x.put("customer",r.getString("customer_name"));x.put("warehouse_id",r.getLong("warehouse_id"));x.put("warehouse",r.getString("warehouse_code"));x.put("amazon_fc_code",r.getString("amazon_fc_code"));x.put("amazon_fc_name",r.getString("fc_name"));x.put("fc_address_missing",r.getObject("amazon_fc_address_id")==null);
        String[] containers=array(r,"containers"),locations=array(r,"locations");List<String> expanded=Arrays.stream(locations).flatMap(v->Arrays.stream(v.split(","))).map(String::trim).filter(v->!v.isBlank()).distinct().sorted().toList();x.put("container_count",containers.length);x.put("containers_preview",Arrays.stream(containers).sorted().limit(5).toList());x.put("location_count",expanded.size());x.put("locations_preview",expanded.stream().limit(8).toList());for(String k:List.of("total_pallet_qty","total_carton_qty","total_weight_lbs","total_cbm")){}x.put("total_pallet_qty",dec(r,"pallets"));x.put("total_carton_qty",dec(r,"cartons"));x.put("total_weight_lbs",dec(r,"weight"));x.put("total_cbm",dec(r,"cbm"));aging(x,r);x.remove("min_aging_days");x.remove("average_aging_days");
        LocalDate inbound=r.getObject("oldest",LocalDate.class);LocalDate earliest=businessDate(r,"earliest");Integer remaining=earliest==null?null:(int)ChronoUnit.DAYS.between(LocalDate.now(BUSINESS_ZONE),earliest);String dispatch=remaining==null||remaining>5?"NORMAL":remaining<=0?"CRITICAL":remaining<=2?"HIGH":"MEDIUM";x.put("inbound_date",inbound);x.put("warehouse_days",inbound==null?null:(int)Math.max(0,ChronoUnit.DAYS.between(inbound,LocalDate.now(BUSINESS_ZONE))));x.put("earliest_outbound_date",earliest);x.put("outbound_days_remaining",remaining);x.put("dispatch_priority",dispatch);x.put("dispatch_priority_rank",List.of("CRITICAL","HIGH","MEDIUM","NORMAL").indexOf(dispatch));
        Object apt=time(r,"ob_appointment");if(apt==null)apt=time(r,"appointment_time");Object sched=time(r,"ob_scheduled");if(sched==null)sched=time(r,"scheduled_pickup_at");x.put("appointment_time",apt);x.put("scheduled_pickup_at",sched);
        x.put("picking_count",r.getInt("picking_count"));x.put("picking_id",nlong(r,"picking_id"));x.put("picking_no",r.getString("picking_no"));x.put("picking_status",nint(r,"picking_status"));x.put("bol_id",nlong(r,"bol_id"));x.put("bol_no",r.getString("bol_no"));x.put("bol_status",nint(r,"bol_status"));x.put("outbound_id",nlong(r,"ob_id"));x.put("outbound_no",r.getString("ob_no"));x.put("outbound_status",nint(r,"ob_status"));
        int status=r.getInt("status");Integer os=nint(r,"ob_status"),ps=nint(r,"picking_status");String stage=(status==8||Objects.equals(os,7)||Objects.equals(ps,5))?"exception":(status==7||Objects.equals(os,5))?"completed":r.getObject("picking_id")==null&&r.getBigDecimal("pallets").signum()>0?"waiting_picking":apt==null?"waiting_appointment":"waiting_outbound";x.put("workbench_stage",stage);x.put("workbench_stage_name",stageName(stage));x.put("has_exception","exception".equals(stage));x.put("status",status);x.put("created_at",time(r,"created_at"));x.put("updated_at",time(r,"updated_at"));return x;
    }

    Optional<List<Map<String,Object>>> findAllocations(long id,UserAccount user){Optional<Map<String,Object>> shipment=find(id,user);return shipment.map(value->allocationRows(id,(String)value.get("amazon_fc_code")));}
    private List<Map<String,Object>> allocationRows(long id,String amazonFcCode){String sql="select a.*,i.lot_no,i.container_number,i.fc_code,i.location_id,i.inbound_date,i.available_pallet_qty,i.available_carton_qty,i.available_weight_lbs,i.available_cbm,l.location_code,l.location_name,u.display_name from fba_inventory_allocations a join inventory_lots i on i.id=a.inventory_lot_id left join warehouse_locations l on l.id=i.location_id join users u on u.id=a.created_by where a.fba_shipment_id=:id order by a.id";return jdbc.query(sql,Map.of("id",id),(r,n)->{Map<String,Object>x=new LinkedHashMap<>();x.put("id",r.getLong("id"));x.put("inventory_lot_id",r.getLong("inventory_lot_id"));for(String k:List.of("lot_no","container_number","fc_code"))x.put(k,r.getString(k));Long lid=nlong(r,"location_id");x.put("location",lid==null?null:ref(lid,r.getString("location_code"),r.getString("location_name")));LocalDate d=r.getObject("inbound_date",LocalDate.class);int age=d==null?0:(int)Math.max(0,ChronoUnit.DAYS.between(d,LocalDate.now(BUSINESS_ZONE)));x.put("inbound_date",d);x.put("aging_days",d==null?null:age);Priority pr=priority(age);x.put("priority_level",d==null?null:pr.level);x.put("priority_label",d==null?null:pr.label);for(String k:List.of("allocated_pallet_qty","allocated_carton_qty","allocated_weight_lbs","allocated_cbm"))x.put(k,dec(r,k));for(String k:List.of("pallet_qty","carton_qty","weight_lbs","cbm"))x.put("inventory_available_"+k,dec(r,"available_"+k));String lotFcCode=r.getString("fc_code");x.put("fc_mismatch",lotFcCode!=null&&!lotFcCode.isBlank()&&!lotFcCode.equalsIgnoreCase(amazonFcCode));x.put("created_by",userRef(r.getLong("created_by"),r.getString("display_name")));x.put("created_at",time(r,"created_at"));x.put("updated_at",time(r,"updated_at"));return x;});}

    private void quantities(Map<String,Object>x,ResultSet r)throws SQLException{x.put("total_pallet_qty",dec(r,"pallets"));x.put("total_carton_qty",dec(r,"cartons"));x.put("total_weight_lbs",dec(r,"weight"));x.put("total_cbm",dec(r,"cbm"));x.put("inventory_lot_count",r.getInt("lot_count"));x.put("containers",Arrays.stream(array(r,"containers")).sorted().toList());}
    private void aging(Map<String,Object>x,ResultSet r)throws SQLException{LocalDate oldest=r.getObject("oldest",LocalDate.class),newest=r.getObject("newest",LocalDate.class);Integer max=oldest==null?null:(int)Math.max(0,ChronoUnit.DAYS.between(oldest,LocalDate.now(BUSINESS_ZONE))),min=newest==null?null:(int)Math.max(0,ChronoUnit.DAYS.between(newest,LocalDate.now(BUSINESS_ZONE)));BigDecimal average=r.getBigDecimal("average_aging");x.put("oldest_inbound_date",oldest);x.put("min_aging_days",min);x.put("max_aging_days",max);x.put("average_aging_days",average==null?null:average.setScale(2,RoundingMode.HALF_UP));Priority pr=max==null?null:priority(max);x.put("priority_level",pr==null?null:pr.level);x.put("priority_label",pr==null?null:pr.label);x.put("priority_range",pr==null?null:pr.range());x.put("priority_rank",pr==null?0:pr.rank);}
    private Priority priority(int days){List<Priority> ps=jdbc.query("select min_days,max_days,priority_level,priority_label,sort_order from inventory_priority_rules where is_active order by sort_order",Map.of(),(r,n)->new Priority(r.getInt(1),nint(r,"max_days"),r.getString(3),r.getString(4),r.getInt(5)));return ps.stream().filter(p->days>=p.min&&(p.max==null||days<=p.max)).findFirst().orElse(new Priority(0,null,null,null,0));}
    private void post(List<Map<String,Object>> rows,String priority,Integer min,Integer max,boolean onlyOld){rows.removeIf(x->{Integer age=(Integer)x.get("max_aging_days");return priority!=null&&!priority.equals(x.get("priority_level"))||min!=null&&(age==null||age<min)||max!=null&&(age==null||age>max)||onlyOld&&(age==null||age<attentionDays());});}
    private Map<String,Object> summary(List<Map<String,Object>> rows){Map<String,Object>x=new LinkedHashMap<>();x.put("task_count",rows.size());for(String k:List.of("total_pallet_qty","total_carton_qty","total_weight_lbs","total_cbm"))x.put(k,rows.stream().map(a->new BigDecimal((String)a.get(k))).reduce(BigDecimal.ZERO,BigDecimal::add).toPlainString());x.put("average_aging_days",rows.stream().map(a->(Integer)a.get("max_aging_days")).filter(Objects::nonNull).mapToInt(i->i).average().isPresent()?BigDecimal.valueOf(rows.stream().map(a->(Integer)a.get("max_aging_days")).filter(Objects::nonNull).mapToInt(i->i).average().orElse(0)):null);return x;}
    private Map<String,Object> page(List<Map<String,Object>> rows,int page,int size){long total=rows.size();int from=Math.min((page-1)*size,rows.size()),to=Math.min(from+size,rows.size());Map<String,Object>x=new LinkedHashMap<>();x.put("data",List.copyOf(rows.subList(from,to)));Map<String,Object>m=new LinkedHashMap<>();m.put("page",page);m.put("per_page",size);m.put("total",total);m.put("total_pages",total==0?0:(total+size-1)/size);x.put("meta",m);return x;}
    @SuppressWarnings({"rawtypes","unchecked"}) private void sort(List<Map<String,Object>> rows,String field,String order){Comparator<Map<String,Object>> c=(a,b)->{Object x=a.get(field),y=b.get(field);if(x==null&&y==null)return 0;if(x==null)return 1;if(y==null)return-1;if(x instanceof Comparable&&x.getClass().equals(y.getClass()))return((Comparable)x).compareTo(y);return String.valueOf(x).compareTo(String.valueOf(y));};c=c.thenComparingLong(x->((Number)x.get("id")).longValue());if("desc".equals(order))c=c.reversed();rows.sort(c);}
    private void scope(UserAccount u,MapSqlParameterSource p,List<String>c){if(!"ADMIN".equals(u.role())&&"SELECTED".equals(u.warehouseScopeMode())){if(u.warehouseIds().isEmpty())c.add("false");else{p.addValue("scope_w",u.warehouseIds());c.add("s.warehouse_id in (:scope_w)");}}if(!"ADMIN".equals(u.role())&&"SELECTED".equals(u.customerScopeMode())){if(u.customerIds().isEmpty())c.add("false");else{p.addValue("scope_c",u.customerIds());c.add("s.customer_id in (:scope_c)");}}}
    private void exact(List<String>c,MapSqlParameterSource p,String k,Object v,String col){if(v!=null){p.addValue(k,v);c.add(col+"=:"+k);}}private void like(List<String>c,MapSqlParameterSource p,String k,String v,String col){if(v!=null){p.addValue(k,"%"+v+"%");c.add(col+" ilike :"+k);}}private void range(List<String>c,MapSqlParameterSource p,String k,String v,String col,String type,boolean low){if(v!=null){p.addValue(k,v);c.add(col+(low?">=":"<=")+"cast(:"+k+" as "+type+")");}}private String where(List<String>c){return c.isEmpty()?"":" where "+String.join(" and ",c);}
    private Map<String,Object> ref(long id,String code,String name){Map<String,Object>x=new LinkedHashMap<>();x.put("id",id);x.put("code",code);x.put("name",name);return x;}private Map<String,Object> userRef(long id,String displayName){Map<String,Object>x=new LinkedHashMap<>();x.put("id",id);x.put("display_name",displayName);return x;}private Map<String,Object> permissions(UserAccount u){return Map.of("can_export",true,"can_operate",Set.of("ADMIN","MANAGER","OUTBOUND","WAREHOUSE").contains(u.role()));}
    private String address(ResultSet r)throws SQLException{return r.getString("address_line1")==null?null:String.join(", ",Arrays.stream(new String[]{r.getString("address_line1"),r.getString("address_line2"),r.getString("fc_city"),r.getString("fc_state"),r.getString("fc_zip"),r.getString("fc_country")}).filter(s->s!=null&&!s.isBlank()).toList());}
    private Map<String,Object> rowMap(ResultSet r)throws SQLException{Map<String,Object>x=new LinkedHashMap<>();ResultSetMetaData md=r.getMetaData();for(int i=1;i<=md.getColumnCount();i++){Object v=r.getObject(i);if(v instanceof Timestamp t)v=t.toInstant().atOffset(ZoneOffset.UTC);if(v instanceof BigDecimal d)v=d.toPlainString();x.put(md.getColumnLabel(i),v);}return x;}
    private List<Map<String,Object>> workflow(String stage,boolean hasPicking,boolean hasBol,Map<String,Object> outbound){boolean apt=outbound!=null&&outbound.get("delivery_appointment_time")!=null;boolean done=outbound!=null&&Objects.equals(((Number)outbound.get("status")).intValue(),5);return List.of(Map.of("key","fba","label","FBA Linked","status","completed"),Map.of("key","picking","label","Picking","status",hasPicking?"completed":"exception".equals(stage)?"exception":"current"),Map.of("key","bol","label","BOL","status",hasBol?"completed":hasPicking?"current":"pending"),Map.of("key","appointment","label","Appointment","status",apt?"completed":hasBol?"current":"pending"),Map.of("key","outbound","label","Outbound","status",done?"completed":apt?"current":"pending"));}
    private int attentionDays(){Integer v=jdbc.query("select min(min_days) from inventory_priority_rules where is_active and min_days>0",Map.of(),r->r.next()?(Integer)r.getObject(1):null);return v==null?8:v;}
    private String stageName(String s){return switch(s){case"waiting_picking"->"Waiting Picking";case"waiting_appointment"->"Waiting Appointment";case"waiting_outbound"->"Waiting Outbound";case"completed"->"Completed";default->"Exception";};}private String statusName(int s){return List.of("Draft","Planning","Allocated","Ready","Scheduled","In Transit","Delivered","Completed","Hold","Canceled").get(Math.max(0,Math.min(9,s)));}
    private String dec(ResultSet r,String k)throws SQLException{BigDecimal d=r.getBigDecimal(k);return(d==null?BigDecimal.ZERO:d).toPlainString();}private Long nlong(ResultSet r,String k)throws SQLException{long v=r.getLong(k);return r.wasNull()?null:v;}private Integer nint(ResultSet r,String k)throws SQLException{int v=r.getInt(k);return r.wasNull()?null:v;}private Object time(ResultSet r,String k)throws SQLException{Timestamp t=r.getTimestamp(k);return t==null?null:t.toInstant().atOffset(ZoneOffset.UTC);}private LocalDate businessDate(ResultSet r,String k)throws SQLException{Timestamp t=r.getTimestamp(k);return t==null?null:t.toInstant().atZone(BUSINESS_ZONE).toLocalDate();}private String[] array(ResultSet r,String k)throws SQLException{Array a=r.getArray(k);return a==null?new String[0]:(String[])a.getArray();}
    private record Priority(int min,Integer max,String level,String label,int rank){String range(){return max==null?min+"d+":min+"-"+max+"d";}}
}
